// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:relay_isolates/rust/api/cancel.dart';
import 'package:relay_isolates/rust/api/model.dart';
import 'package:relay_isolates/rust/api/stream.dart';
import 'package:relay_isolates/rust/frb_generated.dart';

part 'http.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `load_pairing_identity`, `resolve_file_content`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `from`, `from`, `from`

/// Creates an HTTP client.
///
/// `expected_fingerprint` pins the peer to the certificate with that SHA-256
/// fingerprint (uppercase hex). It is enforced during the TLS handshake, so a
/// peer that does not present the expected certificate never receives the
/// request. Pass `None` only for discovery, where the peer is not known yet.
RsHttpClient createClient({
  required String privateKey,
  required String cert,
  required LsHttpClientVersion version,
  String? expectedFingerprint,
  int? timeoutMs,
}) => RustLib.instance.api.crateApiHttpCreateClient(
  privateKey: privateKey,
  cert: cert,
  version: version,
  expectedFingerprint: expectedFingerprint,
  timeoutMs: timeoutMs,
);

/// Runs the mutual Relay LAN pairing handshake against a discovered device.
///
/// `certificate_fingerprint` pins *which socket* is spoken to. It is not an
/// identity: the peer still has to produce a Server-role proof over that exact
/// certificate, and this device still has to produce a Client-role proof over
/// its own, before the remote user is asked anything.
///
/// `expected_relay_id`, when given, is the identity the user targeted. A peer
/// that proves a different one is a hard failure rather than a new device.
Stream<RsRelayLanPairingEvent> relayLanPair({
  required List<int> privateKeyPem,
  required String relayId,
  required String clientPrivateKey,
  required String clientCertificate,
  required LsHttpClientVersion version,
  required ProtocolType protocol,
  required String ip,
  required int port,
  required String certificateFingerprint,
  required String alias,
  String? expectedRelayId,
}) => RustLib.instance.api.crateApiHttpRelayLanPair(
  privateKeyPem: privateKeyPem,
  relayId: relayId,
  clientPrivateKey: clientPrivateKey,
  clientCertificate: clientCertificate,
  version: version,
  protocol: protocol,
  ip: ip,
  port: port,
  certificateFingerprint: certificateFingerprint,
  alias: alias,
  expectedRelayId: expectedRelayId,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsHttpClient>>
abstract class RsHttpClient implements RustOpaqueInterface {
  /// Authenticates the selected HTTPS peer's Relay proof. Rust owns the
  /// nonce, observed TLS certificate fingerprint, and proof verification.
  Future<RsRelayPeerAuth> authenticateRelayServer({required ProtocolType protocol, required String ip, required int port});

  Future<void> cancel({required ProtocolType protocol, required String ip, required int port, required String sessionId});

  Future<PrepareUploadResult> prepareUpload({
    required ProtocolType protocol,
    required String ip,
    required int port,
    required PrepareUploadRequestDto payload,
    String? publicKey,
    String? pin,
    required RsCancellationToken cancelToken,
  });

  Future<ResultWithPublicKeyRegisterResponseDto> register({
    required ProtocolType protocol,
    required String ip,
    required int port,
    required RegisterDto payload,
  });

  /// Uploads a single file, emitting [RsUploadEvent]s on [sink].
  ///
  /// Failures are emitted as [RsUploadEvent::Failed] instead of being
  /// returned: flutter_rust_bridge discards the returned `Result` of
  /// functions taking a [StreamSink], so a returned error would become an
  /// uncaught async error killing the calling isolate.
  Stream<RsUploadEvent> upload({
    required ProtocolType protocol,
    required String ip,
    required int port,
    String? publicKey,
    required String sessionId,
    required String fileId,
    required String token,
    Dart2RustStreamReceiver? binary,
    String? path,
    int? fileDescriptor,
    required BigInt contentLength,
    required RsCancellationToken cancelToken,
  });
}

enum LsHttpClientVersion {
  v2,
  v3,
}

class PrepareUploadResult {
  final int statusCode;
  final PrepareUploadResponseDto? response;

  const PrepareUploadResult({
    required this.statusCode,
    this.response,
  });

  @override
  int get hashCode => statusCode.hashCode ^ response.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrepareUploadResult && runtimeType == other.runtimeType && statusCode == other.statusCode && response == other.response;
}

class ResultWithPublicKeyRegisterResponseDto {
  final String? publicKey;
  final RegisterResponseDto body;

  const ResultWithPublicKeyRegisterResponseDto({
    this.publicKey,
    required this.body,
  });

  @override
  int get hashCode => publicKey.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResultWithPublicKeyRegisterResponseDto && runtimeType == other.runtimeType && publicKey == other.publicKey && body == other.body;
}

@freezed
sealed class RsHttpClientError with _$RsHttpClientError implements FrbException {
  const RsHttpClientError._();

  const factory RsHttpClientError.statusCode({
    required int status,
    String? message,
  }) = RsHttpClientError_StatusCode;
  const factory RsHttpClientError.reqwest(
    String field0,
  ) = RsHttpClientError_Reqwest;
  const factory RsHttpClientError.json(
    String field0,
  ) = RsHttpClientError_Json;
  const factory RsHttpClientError.io(
    String field0,
  ) = RsHttpClientError_Io;
  const factory RsHttpClientError.other(
    String field0,
  ) = RsHttpClientError_Other;
}

@freezed
sealed class RsRelayLanPairingEvent with _$RsRelayLanPairingEvent {
  const RsRelayLanPairingEvent._();

  /// Both identities are proven and the remote user is being asked. Show this
  /// code so both people can confirm they are looking at the same pairing.
  const factory RsRelayLanPairingEvent.verificationCode({
    required String code,
    required String remoteRelayId,
  }) = RsRelayLanPairingEvent_VerificationCode;

  /// The remote user accepted. This is the only outcome that establishes a
  /// relationship, and it still grants no capability.
  const factory RsRelayLanPairingEvent.paired({
    required String remoteRelayId,
    required String remoteAlias,
    required String verificationCode,
  }) = RsRelayLanPairingEvent_Paired;

  /// The remote user rejected. Nothing may be stored.
  const factory RsRelayLanPairingEvent.declined() = RsRelayLanPairingEvent_Declined;

  /// The peer does not support Relay pairing.
  const factory RsRelayLanPairingEvent.unsupported() = RsRelayLanPairingEvent_Unsupported;

  /// The peer is already showing a pairing prompt for another device.
  const factory RsRelayLanPairingEvent.busy() = RsRelayLanPairingEvent_Busy;

  /// An identity proof was missing, wrong, or not the identity we demanded.
  const factory RsRelayLanPairingEvent.authenticationFailed() = RsRelayLanPairingEvent_AuthenticationFailed;

  /// The exchange did not complete. Nothing about identity may be inferred.
  const factory RsRelayLanPairingEvent.transportFailed() = RsRelayLanPairingEvent_TransportFailed;
}

@freezed
sealed class RsRelayPeerAuth with _$RsRelayPeerAuth {
  const RsRelayPeerAuth._();

  const factory RsRelayPeerAuth.notAttempted() = RsRelayPeerAuth_NotAttempted;
  const factory RsRelayPeerAuth.unsupported() = RsRelayPeerAuth_Unsupported;
  const factory RsRelayPeerAuth.transportUnauthenticated() = RsRelayPeerAuth_TransportUnauthenticated;
  const factory RsRelayPeerAuth.signerUnavailable() = RsRelayPeerAuth_SignerUnavailable;
  const factory RsRelayPeerAuth.malformed() = RsRelayPeerAuth_Malformed;
  const factory RsRelayPeerAuth.roleMismatch() = RsRelayPeerAuth_RoleMismatch;
  const factory RsRelayPeerAuth.challengeMismatch() = RsRelayPeerAuth_ChallengeMismatch;
  const factory RsRelayPeerAuth.cryptoInvalid() = RsRelayPeerAuth_CryptoInvalid;
  const factory RsRelayPeerAuth.authenticated({
    required String relayId,
  }) = RsRelayPeerAuth_Authenticated;
}

@freezed
sealed class RsUploadEvent with _$RsUploadEvent {
  const RsUploadEvent._();

  /// The upload progress as a fraction (0.0 to 1.0). Throttled.
  const factory RsUploadEvent.progress({
    required double progress,
  }) = RsUploadEvent_Progress;

  /// The upload failed. Always the last event of the stream.
  const factory RsUploadEvent.failed({
    required RsHttpClientError error,
  }) = RsUploadEvent_Failed;
}
