// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:relay_isolates/rust/frb_generated.dart';

part 'kdeconnect.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `try_from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `_keep_frb_imports`

Future<RsKdeConnectIdentity> kdeconnectGenerateIdentity({required String deviceName}) =>
    RustLib.instance.api.crateApiKdeconnectKdeconnectGenerateIdentity(deviceName: deviceName);

Future<RsKdeConnect> startKdeconnect({required RsKdeConnectIdentity identity, required List<RsKdeConnectTrustedDevice> trusted}) =>
    RustLib.instance.api.crateApiKdeconnectStartKdeconnect(identity: identity, trusted: trusted);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsKdeConnect>>
abstract class RsKdeConnect implements RustOpaqueInterface {
  Future<void> acceptPair({required String deviceId});

  Future<void> findPhone({required String deviceId});

  Future<List<RsKdeNotification>> getNotifications({required String deviceId});

  Stream<RsKdeConnectEvent> listen();

  Future<void> rejectPair({required String deviceId});

  Future<void> requestNotifications({required String deviceId});

  Future<void> requestPair({required String deviceId});

  Future<void> sendClipboard({required String deviceId, required String content, required PlatformInt64 timestampMs});

  Future<void> sendClipboardToAllPaired({required String content, required PlatformInt64 timestampMs});

  Future<void> sendPing({required String deviceId, String? message});

  Future<List<RsKdeConnectDevice>> snapshot();

  Future<void> stop();

  Future<void> unpair({required String deviceId});
}

class RsKdeConnectDevice {
  final String deviceId;
  final String name;
  final String deviceType;
  final String? ip;
  final int? port;
  final bool paired;
  final bool connected;
  final bool incomingPair;
  final bool identityMismatch;
  final int? batteryPercentage;
  final bool? batteryIsCharging;
  final String? networkType;
  final int? signalLevel;
  final bool connectivityStale;
  final List<String> incomingCapabilities;
  final List<String> outgoingCapabilities;

  const RsKdeConnectDevice({
    required this.deviceId,
    required this.name,
    required this.deviceType,
    this.ip,
    this.port,
    required this.paired,
    required this.connected,
    required this.incomingPair,
    required this.identityMismatch,
    this.batteryPercentage,
    this.batteryIsCharging,
    this.networkType,
    this.signalLevel,
    required this.connectivityStale,
    required this.incomingCapabilities,
    required this.outgoingCapabilities,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      name.hashCode ^
      deviceType.hashCode ^
      ip.hashCode ^
      port.hashCode ^
      paired.hashCode ^
      connected.hashCode ^
      incomingPair.hashCode ^
      identityMismatch.hashCode ^
      batteryPercentage.hashCode ^
      batteryIsCharging.hashCode ^
      networkType.hashCode ^
      signalLevel.hashCode ^
      connectivityStale.hashCode ^
      incomingCapabilities.hashCode ^
      outgoingCapabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsKdeConnectDevice &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          name == other.name &&
          deviceType == other.deviceType &&
          ip == other.ip &&
          port == other.port &&
          paired == other.paired &&
          connected == other.connected &&
          incomingPair == other.incomingPair &&
          identityMismatch == other.identityMismatch &&
          batteryPercentage == other.batteryPercentage &&
          batteryIsCharging == other.batteryIsCharging &&
          networkType == other.networkType &&
          signalLevel == other.signalLevel &&
          connectivityStale == other.connectivityStale &&
          incomingCapabilities == other.incomingCapabilities &&
          outgoingCapabilities == other.outgoingCapabilities;
}

@freezed
sealed class RsKdeConnectEvent with _$RsKdeConnectEvent {
  const RsKdeConnectEvent._();

  const factory RsKdeConnectEvent.devicesChanged({
    required List<RsKdeConnectDevice> devices,
  }) = RsKdeConnectEvent_DevicesChanged;
  const factory RsKdeConnectEvent.incomingPair({
    required String deviceId,
    required String name,
  }) = RsKdeConnectEvent_IncomingPair;
  const factory RsKdeConnectEvent.pairingFailed({
    required String deviceId,
    required String reason,
  }) = RsKdeConnectEvent_PairingFailed;
  const factory RsKdeConnectEvent.trustChanged({
    required List<RsKdeConnectTrustedDevice> devices,
  }) = RsKdeConnectEvent_TrustChanged;
  const factory RsKdeConnectEvent.pingReceived({
    required String deviceId,
    String? message,
  }) = RsKdeConnectEvent_PingReceived;
  const factory RsKdeConnectEvent.clipboardReceived({
    required String deviceId,
    required String content,
    required PlatformInt64 timestampMs,
  }) = RsKdeConnectEvent_ClipboardReceived;
  const factory RsKdeConnectEvent.notificationsChanged({
    required String deviceId,
    required List<RsKdeNotification> notifications,
  }) = RsKdeConnectEvent_NotificationsChanged;
}

class RsKdeConnectIdentity {
  final String deviceId;
  final String deviceName;
  final String certificatePem;
  final String privateKeyPem;

  const RsKdeConnectIdentity({
    required this.deviceId,
    required this.deviceName,
    required this.certificatePem,
    required this.privateKeyPem,
  });

  @override
  int get hashCode => deviceId.hashCode ^ deviceName.hashCode ^ certificatePem.hashCode ^ privateKeyPem.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsKdeConnectIdentity &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          certificatePem == other.certificatePem &&
          privateKeyPem == other.privateKeyPem;
}

class RsKdeConnectTrustedDevice {
  final String deviceId;
  final String certificatePem;
  final String name;
  final String deviceType;
  final PlatformInt64 protocolVersion;
  final PlatformInt64 pairedAtUnix;

  const RsKdeConnectTrustedDevice({
    required this.deviceId,
    required this.certificatePem,
    required this.name,
    required this.deviceType,
    required this.protocolVersion,
    required this.pairedAtUnix,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ certificatePem.hashCode ^ name.hashCode ^ deviceType.hashCode ^ protocolVersion.hashCode ^ pairedAtUnix.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsKdeConnectTrustedDevice &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          certificatePem == other.certificatePem &&
          name == other.name &&
          deviceType == other.deviceType &&
          protocolVersion == other.protocolVersion &&
          pairedAtUnix == other.pairedAtUnix;
}

class RsKdeNotification {
  final String id;
  final String? appName;
  final String? title;
  final String? text;
  final String? time;
  final bool isClearable;
  final bool silent;

  const RsKdeNotification({
    required this.id,
    this.appName,
    this.title,
    this.text,
    this.time,
    required this.isClearable,
    required this.silent,
  });

  @override
  int get hashCode => id.hashCode ^ appName.hashCode ^ title.hashCode ^ text.hashCode ^ time.hashCode ^ isClearable.hashCode ^ silent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsKdeNotification &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          appName == other.appName &&
          title == other.title &&
          text == other.text &&
          time == other.time &&
          isClearable == other.isClearable &&
          silent == other.silent;
}
