display_name: Relay
packager: Aritra Saha
packagerEmail: aritrasab@gmail.com
url: https://github.com/iamaritrasaha/relay
buildArch: x86_64
license: Apache-2.0

icon: assets/img/relay-icon-linux-512.png

requires:
  - libappindicator
  - xdg-user-dirs

keywords:
  - Sharing
  - LAN
  - Files

generic_name: Share files securely across your devices
summary: Share files easily with Relay
group: Applications/Utilities

categories:
  - GTK
  - FileTransfer
  - Utility

startup_notify: true
