// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:localsend_isolates/rust/frb_generated.dart';

part 'continuity.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `_protocol_surface`, `event_sink`, `listener_accept_config`, `map_action_out`, `map_capability_in`, `map_charging_in`, `map_conversation`, `map_end`, `map_event`, `map_message`, `map_phase_in`, `map_state_in`, `publish_all`, `publish_to`, `runtime`, `session_config`, `spawn_host_pump`, `split_host_request`, `take_pending`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AppTrustDirectory`, `ContinuityRuntime`, `PendingReply`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `lookup`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Registers the continuity event stream. Called once, at app start.
Stream<RsContinuityEvent> continuityEvents() => RustLib.instance.api.crateApiContinuityContinuityEvents();

/// Registers the stream of authorized work a peer asks this device to perform.
Stream<RsContinuityHostRequest> continuityHostRequests() => RustLib.instance.api.crateApiContinuityContinuityHostRequests();

/// Publishes what this installation can actually do.
///
/// The app computes these states from real platform permission checks; nothing
/// here invents availability.
void continuitySetLocalCapabilities({required String deviceLabel, required String platform, required List<RsCapabilityEntry> entries}) =>
    RustLib.instance.api.crateApiContinuityContinuitySetLocalCapabilities(deviceLabel: deviceLabel, platform: platform, entries: entries);

/// Replaces the trusted/blocked device sets from persisted user decisions.
void continuitySetDeviceTrust({required List<String> trusted, required List<String> blocked}) =>
    RustLib.instance.api.crateApiContinuityContinuitySetDeviceTrust(trusted: trusted, blocked: blocked);

/// Enables one capability for one device. This is the user consent point;
/// pairing never calls it implicitly.
Future<void> continuityEnableCapability({required String relayId, required RsContinuityCapability capability}) =>
    RustLib.instance.api.crateApiContinuityContinuityEnableCapability(relayId: relayId, capability: capability);

Future<void> continuityDisableCapability({required String relayId, required RsContinuityCapability capability}) =>
    RustLib.instance.api.crateApiContinuityContinuityDisableCapability(relayId: relayId, capability: capability);

Future<void> continuitySetClipboardMode({required String relayId, required RsClipboardMode mode}) =>
    RustLib.instance.api.crateApiContinuityContinuitySetClipboardMode(relayId: relayId, mode: mode);

/// Serialises the permission store so the app can persist it verbatim.
Future<String> continuityExportPermissions() => RustLib.instance.api.crateApiContinuityContinuityExportPermissions();

/// Restores a previously exported permission store. Malformed input leaves the
/// store empty (all denied) rather than partially applied.
Future<bool> continuityImportPermissions({required String json}) => RustLib.instance.api.crateApiContinuityContinuityImportPermissions(json: json);

/// Whether any device has any continuity capability enabled.
///
/// Android uses this to decide whether a background service should exist at
/// all: a fresh install answers `false`.
Future<bool> continuityAnyCapabilityEnabled() => RustLib.instance.api.crateApiContinuityContinuityAnyCapabilityEnabled();

/// Whether a live, authenticated continuity session exists with a device.
/// A stored Relay address alone never makes this true.
bool continuityIsConnected({required String relayId}) => RustLib.instance.api.crateApiContinuityContinuityIsConnected(relayId: relayId);

List<String> continuityConnectedDevices() => RustLib.instance.api.crateApiContinuityContinuityConnectedDevices();

/// Opens and maintains an outbound continuity link to one paired device.
///
/// The Relay private key comes from the platform secret store and is wiped
/// here. No routing key is needed: continuity rides the endpoint the Anywhere
/// listener already bound, so there is one routing identity per device.
Future<void> continuityConnectDevice({required List<int> privateKeyPem, required String relayId, required String remoteAddress}) =>
    RustLib.instance.api.crateApiContinuityContinuityConnectDevice(privateKeyPem: privateKeyPem, relayId: relayId, remoteAddress: remoteAddress);

/// Stops the continuity link with one device without affecting others.
void continuityDisconnectDevice({required String relayId}) => RustLib.instance.api.crateApiContinuityContinuityDisconnectDevice(relayId: relayId);

/// Stops every continuity link. Called when the user turns continuity off, and
/// on app shutdown.
void continuityDisconnectAll() => RustLib.instance.api.crateApiContinuityContinuityDisconnectAll();

/// Publishes local battery state. Call only on a meaningful change.
Future<void> continuityPublishBattery({int? percentage, required RsChargingState charging}) =>
    RustLib.instance.api.crateApiContinuityContinuityPublishBattery(percentage: percentage, charging: charging);

/// Shares local clipboard text. `explicit` marks a user-initiated share, which
/// is surfaced for confirmation on the peer even in Ask mode.
Future<void> continuityShareClipboard({required String text, required bool explicit, required String originRelayId}) =>
    RustLib.instance.api.crateApiContinuityContinuityShareClipboard(text: text, explicit: explicit, originRelayId: originRelayId);

Future<void> continuityPublishNotification({
  required String key,
  required String appLabel,
  String? title,
  String? body,
  required BigInt postedAtMs,
  required bool clearable,
}) => RustLib.instance.api.crateApiContinuityContinuityPublishNotification(
  key: key,
  appLabel: appLabel,
  title: title,
  body: body,
  postedAtMs: postedAtMs,
  clearable: clearable,
);

Future<void> continuityPublishNotificationRemoved({required String key}) =>
    RustLib.instance.api.crateApiContinuityContinuityPublishNotificationRemoved(key: key);

Future<void> continuityPublishCallState({required RsCallPhase phase, String? address, String? displayName, BigInt? activeDurationMs}) => RustLib
    .instance
    .api
    .crateApiContinuityContinuityPublishCallState(phase: phase, address: address, displayName: displayName, activeDurationMs: activeDurationMs);

/// Streams one newly received message to peers that mirror this device.
Future<void> continuityPublishIncomingMessage({
  required String conversationId,
  required String messageId,
  String? address,
  required String body,
  required BigInt sentAtMs,
}) => RustLib.instance.api.crateApiContinuityContinuityPublishIncomingMessage(
  conversationId: conversationId,
  messageId: messageId,
  address: address,
  body: body,
  sentAtMs: sentAtMs,
);

Future<bool> continuityRequestConversations({required String relayId, required int limit, BigInt? beforeMs}) =>
    RustLib.instance.api.crateApiContinuityContinuityRequestConversations(relayId: relayId, limit: limit, beforeMs: beforeMs);

Future<bool> continuityRequestMessages({required String relayId, required String conversationId, required int limit, BigInt? beforeMs}) => RustLib
    .instance
    .api
    .crateApiContinuityContinuityRequestMessages(relayId: relayId, conversationId: conversationId, limit: limit, beforeMs: beforeMs);

/// Asks a peer to send a message. `request_id` makes the send idempotent, so a
/// retry after a reconnect is answered rather than sent twice.
Future<bool> continuitySendSms({
  required String relayId,
  required String requestId,
  String? conversationId,
  required List<String> recipients,
  required String body,
}) => RustLib.instance.api.crateApiContinuityContinuitySendSms(
  relayId: relayId,
  requestId: requestId,
  conversationId: conversationId,
  recipients: recipients,
  body: body,
);

Future<bool> continuityCallAction({required String relayId, required String requestId, required RsCallAction action, String? address}) =>
    RustLib.instance.api.crateApiContinuityContinuityCallAction(relayId: relayId, requestId: requestId, action: action, address: address);

Future<bool> continuityDismissRemoteNotification({required String relayId, required String key}) =>
    RustLib.instance.api.crateApiContinuityContinuityDismissRemoteNotification(relayId: relayId, key: key);

void continuityAnswerAck({required BigInt requestId}) => RustLib.instance.api.crateApiContinuityContinuityAnswerAck(requestId: requestId);

void continuityAnswerConversations({required BigInt requestId, required List<RsSmsConversation> conversations, required bool hasMore}) =>
    RustLib.instance.api.crateApiContinuityContinuityAnswerConversations(requestId: requestId, conversations: conversations, hasMore: hasMore);

void continuityAnswerMessages({
  required BigInt requestId,
  required String conversationId,
  required List<RsSmsMessage> messages,
  required bool hasMore,
}) => RustLib.instance.api.crateApiContinuityContinuityAnswerMessages(
  requestId: requestId,
  conversationId: conversationId,
  messages: messages,
  hasMore: hasMore,
);

/// Reports that a capability could not be served, with an honest reason.
void continuityAnswerUnavailable({required BigInt requestId, required bool permissionRequired, required String detail}) =>
    RustLib.instance.api.crateApiContinuityContinuityAnswerUnavailable(requestId: requestId, permissionRequired: permissionRequired, detail: detail);

void continuityAnswerSmsSent({required BigInt requestId, String? messageId}) =>
    RustLib.instance.api.crateApiContinuityContinuityAnswerSmsSent(requestId: requestId, messageId: messageId);

void continuityAnswerSmsFailed({required BigInt requestId, required String reason}) =>
    RustLib.instance.api.crateApiContinuityContinuityAnswerSmsFailed(requestId: requestId, reason: reason);

void continuityAnswerCallAction({required BigInt requestId, required bool accepted, required String reason}) =>
    RustLib.instance.api.crateApiContinuityContinuityAnswerCallAction(requestId: requestId, accepted: accepted, reason: reason);

enum RsCallAction {
  dial,
  answer,
  reject,
  hangUp,
}

enum RsCallPhase {
  idle,
  ringing,
  dialing,
  active,
  ended,
  unknown,
}

class RsCallState {
  final RsCallPhase phase;
  final String? address;
  final String? displayName;
  final BigInt? activeDurationMs;

  const RsCallState({
    required this.phase,
    this.address,
    this.displayName,
    this.activeDurationMs,
  });

  @override
  int get hashCode => phase.hashCode ^ address.hashCode ^ displayName.hashCode ^ activeDurationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsCallState &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          address == other.address &&
          displayName == other.displayName &&
          activeDurationMs == other.activeDurationMs;
}

class RsCapabilityEntry {
  final RsContinuityCapability capability;
  final RsCapabilityState state;

  const RsCapabilityEntry({
    required this.capability,
    required this.state,
  });

  @override
  int get hashCode => capability.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsCapabilityEntry && runtimeType == other.runtimeType && capability == other.capability && state == other.state;
}

class RsCapabilityManifest {
  final String deviceLabel;
  final String platform;
  final List<RsCapabilityEntry> entries;

  const RsCapabilityManifest({
    required this.deviceLabel,
    required this.platform,
    required this.entries,
  });

  @override
  int get hashCode => deviceLabel.hashCode ^ platform.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsCapabilityManifest &&
          runtimeType == other.runtimeType &&
          deviceLabel == other.deviceLabel &&
          platform == other.platform &&
          entries == other.entries;
}

@freezed
sealed class RsCapabilityState with _$RsCapabilityState {
  const RsCapabilityState._();

  const factory RsCapabilityState.available() = RsCapabilityState_Available;
  const factory RsCapabilityState.permissionRequired({
    required String reason,
  }) = RsCapabilityState_PermissionRequired;
  const factory RsCapabilityState.limited({
    required String reason,
  }) = RsCapabilityState_Limited;
  const factory RsCapabilityState.unavailable({
    required String reason,
  }) = RsCapabilityState_Unavailable;
}

enum RsChargingState {
  discharging,
  charging,
  full,
  notCharging,
  unknown,
}

enum RsClipboardMode {
  off,
  ask,
  automatic,
}

enum RsContinuityCapability {
  battery,
  clipboard,
  notifications,
  messages,
  phone,
}

@freezed
sealed class RsContinuityEvent with _$RsContinuityEvent {
  const RsContinuityEvent._();

  const factory RsContinuityEvent.sessionEstablished({
    required String remoteRelayId,
    required bool directPath,
  }) = RsContinuityEvent_SessionEstablished;
  const factory RsContinuityEvent.sessionEnded({
    required String remoteRelayId,
    required String reason,
  }) = RsContinuityEvent_SessionEnded;
  const factory RsContinuityEvent.manifestReceived({
    required String remoteRelayId,
    required RsCapabilityManifest manifest,
  }) = RsContinuityEvent_ManifestReceived;
  const factory RsContinuityEvent.batteryChanged({
    required String remoteRelayId,
    int? percentage,
    required RsChargingState charging,
  }) = RsContinuityEvent_BatteryChanged;
  const factory RsContinuityEvent.clipboardOffered({
    required String remoteRelayId,
    required String text,
    required bool explicit,
  }) = RsContinuityEvent_ClipboardOffered;
  const factory RsContinuityEvent.notificationPosted({
    required String remoteRelayId,
    required String key,
    required String appLabel,
    String? title,
    String? body,
    required BigInt postedAtMs,
    required bool clearable,
  }) = RsContinuityEvent_NotificationPosted;
  const factory RsContinuityEvent.notificationRemoved({
    required String remoteRelayId,
    required String key,
  }) = RsContinuityEvent_NotificationRemoved;
  const factory RsContinuityEvent.conversationsPage({
    required String remoteRelayId,
    required List<RsSmsConversation> conversations,
    required bool hasMore,
  }) = RsContinuityEvent_ConversationsPage;
  const factory RsContinuityEvent.messagesPage({
    required String remoteRelayId,
    required String conversationId,
    required List<RsSmsMessage> messages,
    required bool hasMore,
  }) = RsContinuityEvent_MessagesPage;
  const factory RsContinuityEvent.messageReceived({
    required String remoteRelayId,
    required RsSmsMessage message,
  }) = RsContinuityEvent_MessageReceived;
  const factory RsContinuityEvent.smsSendCompleted({
    required String remoteRelayId,
    required String requestId,
    required bool sent,
    String? detail,
  }) = RsContinuityEvent_SmsSendCompleted;
  const factory RsContinuityEvent.callStateChanged({
    required String remoteRelayId,
    required RsCallState state,
  }) = RsContinuityEvent_CallStateChanged;
  const factory RsContinuityEvent.callActionCompleted({
    required String remoteRelayId,
    required String requestId,
    required bool accepted,
    String? detail,
  }) = RsContinuityEvent_CallActionCompleted;
  const factory RsContinuityEvent.peerError({
    required String remoteRelayId,
    required String code,
    required String detail,
  }) = RsContinuityEvent_PeerError;
}

@freezed
sealed class RsContinuityHostRequest with _$RsContinuityHostRequest {
  const RsContinuityHostRequest._();

  const factory RsContinuityHostRequest.applyClipboard({
    required BigInt requestId,
    required String remoteRelayId,
    required String text,
  }) = RsContinuityHostRequest_ApplyClipboard;
  const factory RsContinuityHostRequest.dismissNotification({
    required BigInt requestId,
    required String remoteRelayId,
    required String key,
  }) = RsContinuityHostRequest_DismissNotification;
  const factory RsContinuityHostRequest.listConversations({
    required BigInt requestId,
    required String remoteRelayId,
    required int limit,
    BigInt? beforeMs,
  }) = RsContinuityHostRequest_ListConversations;
  const factory RsContinuityHostRequest.listMessages({
    required BigInt requestId,
    required String remoteRelayId,
    required String conversationId,
    required int limit,
    BigInt? beforeMs,
  }) = RsContinuityHostRequest_ListMessages;
  const factory RsContinuityHostRequest.sendSms({
    required BigInt requestId,
    required String remoteRelayId,
    String? conversationId,
    required List<String> recipients,
    required String body,
  }) = RsContinuityHostRequest_SendSms;
  const factory RsContinuityHostRequest.callAction({
    required BigInt requestId,
    required String remoteRelayId,
    required RsCallAction action,
    String? address,
  }) = RsContinuityHostRequest_CallAction;
}

class RsSmsConversation {
  final String conversationId;
  final String? displayName;
  final List<String> addresses;
  final String? snippet;
  final BigInt lastMessageAtMs;
  final bool unread;

  const RsSmsConversation({
    required this.conversationId,
    this.displayName,
    required this.addresses,
    this.snippet,
    required this.lastMessageAtMs,
    required this.unread,
  });

  @override
  int get hashCode =>
      conversationId.hashCode ^ displayName.hashCode ^ addresses.hashCode ^ snippet.hashCode ^ lastMessageAtMs.hashCode ^ unread.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsSmsConversation &&
          runtimeType == other.runtimeType &&
          conversationId == other.conversationId &&
          displayName == other.displayName &&
          addresses == other.addresses &&
          snippet == other.snippet &&
          lastMessageAtMs == other.lastMessageAtMs &&
          unread == other.unread;
}

class RsSmsMessage {
  final String conversationId;
  final String messageId;
  final bool outgoing;
  final String? address;
  final String body;
  final BigInt sentAtMs;
  final bool read;

  const RsSmsMessage({
    required this.conversationId,
    required this.messageId,
    required this.outgoing,
    this.address,
    required this.body,
    required this.sentAtMs,
    required this.read,
  });

  @override
  int get hashCode =>
      conversationId.hashCode ^ messageId.hashCode ^ outgoing.hashCode ^ address.hashCode ^ body.hashCode ^ sentAtMs.hashCode ^ read.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsSmsMessage &&
          runtimeType == other.runtimeType &&
          conversationId == other.conversationId &&
          messageId == other.messageId &&
          outgoing == other.outgoing &&
          address == other.address &&
          body == other.body &&
          sentAtMs == other.sentAtMs &&
          read == other.read;
}
