// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:localsend_isolates/rust/frb_generated.dart';

part 'ra2b.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `run_session`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Returns this process's in-memory development RelayId. Not a stored favorite.
RsRa2bLocalIdentity ra2BLocalIdentity() => RustLib.instance.api.crateApiRa2BRa2BLocalIdentity();

/// Parses a development invite. Fail-closed; never panics on bad input.
RsRa2bParsedInvite ra2BParseInvite({required String invite}) => RustLib.instance.api.crateApiRa2BRa2BParseInvite(invite: invite);

bool ra2BSessionIsActive() => RustLib.instance.api.crateApiRa2BRa2BSessionIsActive();

/// Cancels the single active host or join session, if any.
void ra2BCancelSession() => RustLib.instance.api.crateApiRa2BRa2BCancelSession();

/// Configures the one real file used by the RA4A sender test.
void ra4SetSender({String? path, int? fileDescriptor, required String name, required BigInt size, required String fileType, String? sha256}) =>
    RustLib.instance.api.crateApiRa2BRa4SetSender(
      path: path,
      fileDescriptor: fileDescriptor,
      name: name,
      size: size,
      fileType: fileType,
      sha256: sha256,
    );

/// Configures the RA4A receiver test; approval supplies the save target.
void ra4SetReceiver() => RustLib.instance.api.crateApiRa2BRa4SetReceiver();

void ra4Clear() => RustLib.instance.api.crateApiRa2BRa4Clear();

void ra4Respond({required bool accept, String? targetPath}) => RustLib.instance.api.crateApiRa2BRa4Respond(accept: accept, targetPath: targetPath);

/// Starts the in-process RA2B host (responder). Emits invite + progress events.
Stream<RsRa2bEvent> ra2BStartHost({required RsRa2bPathPreference pathPreference, required bool wrongIdentity}) =>
    RustLib.instance.api.crateApiRa2BRa2BStartHost(pathPreference: pathPreference, wrongIdentity: wrongIdentity);

/// Join using a development invite. `wrong_identity` mutates expected host RelayId.
Stream<RsRa2bEvent> ra2BRunJoin({required String invite, required RsRa2bPathPreference pathPreference, required bool wrongIdentity}) =>
    RustLib.instance.api.crateApiRa2BRa2BRunJoin(invite: invite, pathPreference: pathPreference, wrongIdentity: wrongIdentity);

@freezed
sealed class RsRa2bEvent with _$RsRa2bEvent {
  const RsRa2bEvent._();

  const factory RsRa2bEvent.starting() = RsRa2bEvent_Starting;
  const factory RsRa2bEvent.inviteReady({
    required String invite,
    required String localRelayId,
    required bool autoRelayAvailable,
  }) = RsRa2bEvent_InviteReady;
  const factory RsRa2bEvent.waitingForPeer() = RsRa2bEvent_WaitingForPeer;
  const factory RsRa2bEvent.connecting() = RsRa2bEvent_Connecting;
  const factory RsRa2bEvent.irohConnected() = RsRa2bEvent_IrohConnected;
  const factory RsRa2bEvent.tlsAuthenticated() = RsRa2bEvent_TlsAuthenticated;
  const factory RsRa2bEvent.relayIdentityVerified({
    required String remoteRelayId,
  }) = RsRa2bEvent_RelayIdentityVerified;
  const factory RsRa2bEvent.transferring({
    required BigInt bytes,
    required BigInt total,
  }) = RsRa2bEvent_Transferring;
  const factory RsRa2bEvent.complete({
    required String path,
    required int bytes,
    required String hashHex,
    required String localRelayId,
    required String remoteRelayId,
    required BigInt durationMs,
  }) = RsRa2bEvent_Complete;
  const factory RsRa2bEvent.rejected({
    required String message,
    required String category,
  }) = RsRa2bEvent_Rejected;
  const factory RsRa2bEvent.failed({
    required String message,
    required String category,
  }) = RsRa2bEvent_Failed;
  const factory RsRa2bEvent.cancelled() = RsRa2bEvent_Cancelled;
}

class RsRa2bLocalIdentity {
  final String relayId;

  const RsRa2bLocalIdentity({
    required this.relayId,
  });

  @override
  int get hashCode => relayId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is RsRa2bLocalIdentity && runtimeType == other.runtimeType && relayId == other.relayId;
}

class RsRa2bParsedInvite {
  final int version;
  final String hostRelayId;
  final bool routingAvailable;

  /// Short session capability label (development only).
  final String? capability;

  const RsRa2bParsedInvite({
    required this.version,
    required this.hostRelayId,
    required this.routingAvailable,
    this.capability,
  });

  @override
  int get hashCode => version.hashCode ^ hostRelayId.hashCode ^ routingAvailable.hashCode ^ capability.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsRa2bParsedInvite &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          hostRelayId == other.hostRelayId &&
          routingAvailable == other.routingAvailable &&
          capability == other.capability;
}

enum RsRa2bPathPreference {
  auto,
  forceRelay,
}
