// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:localsend_isolates/rust/frb_generated.dart';

part 'relay_anywhere.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `anywhere_listener`, `anywhere_runtime`, `file_spec`, `finish`, `map_event`, `map_failure`, `map_listener_event`, `session_cancellation`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RsRelayAnywhereSaveTarget`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Parses a Relay address bundle. Fail-closed; never panics on bad input.
RsRelayAddress relayAnywhereParseAddress({required String address}) =>
    RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereParseAddress(address: address);

/// Creates an opaque private routing key for a persistent Anywhere endpoint.
///
/// The caller must immediately place this material in the platform secret
/// store. It is intentionally unrelated to the Relay identity private key.
Uint8List relayAnywhereGenerateRoutingKey() => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereGenerateRoutingKey();

/// Validates opaque routing-key material before it is used or retained.
/// No endpoint is bound and no routing metadata is exposed by this operation.
void relayAnywhereValidateRoutingKey({required List<int> routingKey}) =>
    RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereValidateRoutingKey(routingKey: routingKey);

/// Activates the single reusable Anywhere listener. This is the production
/// capability boundary: importing the API or opening an outbound session does
/// not bind Iroh. The caller supplies both unrelated secret materials from the
/// platform stores, and they are wiped after being reconstructed in Rust.
Stream<RsRelayAnywhereListenerEvent> relayAnywhereStartListener({
  required List<int> privateKeyPem,
  required String relayId,
  required List<int> routingKey,
  required String alias,
}) => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereStartListener(
  privateKeyPem: privateKeyPem,
  relayId: relayId,
  routingKey: routingKey,
  alias: alias,
);

/// Stops remote capability and cleanly closes the persistent endpoint. It is
/// idempotent so normal application shutdown can call it unconditionally.
Future<void> relayAnywhereStopListener() => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereStopListener();

/// Returns the current public routing address without exposing its private key.
String? relayAnywhereListenerAddress() => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereListenerAddress();

/// Opens a session handle. Any number may be open at once.
BigInt relayAnywhereOpenSession() => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereOpenSession();

/// Cancels exactly one session. Other sessions are unaffected.
bool relayAnywhereCancel({required BigInt sessionId}) => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereCancel(sessionId: sessionId);

/// Drops one session handle after it finished.
bool relayAnywhereCloseSession({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereCloseSession(sessionId: sessionId);

int relayAnywhereOpenSessionCount() => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereOpenSessionCount();

/// Answers one specific inbound request.
///
/// Accepting is session-scoped consent for this transfer only; it never becomes
/// persistent trust.
void relayAnywhereRespond({required BigInt sessionId, required BigInt transferId, required bool accept, String? targetsJson}) => RustLib.instance.api
    .crateApiRelayAnywhereRelayAnywhereRespond(sessionId: sessionId, transferId: transferId, accept: accept, targetsJson: targetsJson);

/// Receives one authenticated Anywhere transfer on `session_id`.
///
/// `private_key_pem` is the persisted Relay identity key from the platform
/// secret store. It is zeroed inside Rust before this call returns.
Stream<RsRelayAnywhereEvent> relayAnywhereReceive({
  required BigInt sessionId,
  required List<int> privateKeyPem,
  required String relayId,
  required String alias,
  required RsRelayPathPreference pathPreference,
  String? expectedRemoteRelayId,
}) => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereReceive(
  sessionId: sessionId,
  privateKeyPem: privateKeyPem,
  relayId: relayId,
  alias: alias,
  pathPreference: pathPreference,
  expectedRemoteRelayId: expectedRemoteRelayId,
);

/// Sends one authenticated Anywhere batch on `session_id`.
Stream<RsRelayAnywhereEvent> relayAnywhereSend({
  required BigInt sessionId,
  required List<int> privateKeyPem,
  required String relayId,
  required String address,
  required String alias,
  required RsRelayPathPreference pathPreference,
  required List<RsRelayAnywhereFile> files,
}) => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereSend(
  sessionId: sessionId,
  privateKeyPem: privateKeyPem,
  relayId: relayId,
  address: address,
  alias: alias,
  pathPreference: pathPreference,
  files: files,
);

/// Authenticates an address claim before pairing it. This sends no payload and
/// never persists routing metadata itself; Dart only records the route after a
/// successful proof of the claimed RelayId.
Stream<RsRelayAnywhereEvent> relayAnywhereAuthenticateAddress({
  required BigInt sessionId,
  required List<int> privateKeyPem,
  required String relayId,
  required String address,
  required RsRelayPathPreference pathPreference,
}) => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereAuthenticateAddress(
  sessionId: sessionId,
  privateKeyPem: privateKeyPem,
  relayId: relayId,
  address: address,
  pathPreference: pathPreference,
);

/// A parsed Relay address. `claimedRelayId` is a claim to be proven by the
/// session, never evidence of identity or trust.
class RsRelayAddress {
  final int version;
  final String claimedRelayId;
  final bool routingAvailable;

  const RsRelayAddress({
    required this.version,
    required this.claimedRelayId,
    required this.routingAvailable,
  });

  @override
  int get hashCode => version.hashCode ^ claimedRelayId.hashCode ^ routingAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsRelayAddress &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          claimedRelayId == other.claimedRelayId &&
          routingAvailable == other.routingAvailable;
}

@freezed
sealed class RsRelayAnywhereEvent with _$RsRelayAnywhereEvent {
  const RsRelayAnywhereEvent._();

  const factory RsRelayAnywhereEvent.starting() = RsRelayAnywhereEvent_Starting;
  const factory RsRelayAnywhereEvent.addressReady({
    required String address,
    required String localRelayId,
  }) = RsRelayAnywhereEvent_AddressReady;
  const factory RsRelayAnywhereEvent.waitingForPeer() = RsRelayAnywhereEvent_WaitingForPeer;
  const factory RsRelayAnywhereEvent.connecting() = RsRelayAnywhereEvent_Connecting;
  const factory RsRelayAnywhereEvent.peerConnected() = RsRelayAnywhereEvent_PeerConnected;
  const factory RsRelayAnywhereEvent.tlsEstablished() = RsRelayAnywhereEvent_TlsEstablished;
  const factory RsRelayAnywhereEvent.peerAuthenticated({
    required String remoteRelayId,
  }) = RsRelayAnywhereEvent_PeerAuthenticated;
  const factory RsRelayAnywhereEvent.incomingBatch({
    required BigInt transferId,
    required List<RsRelayIncomingFile> files,
    required String remoteRelayId,
  }) = RsRelayAnywhereEvent_IncomingBatch;
  const factory RsRelayAnywhereEvent.transferring({
    required BigInt bytes,
    required BigInt total,
  }) = RsRelayAnywhereEvent_Transferring;
  const factory RsRelayAnywhereEvent.completed({
    required String path,
    required BigInt bytes,
    required String localRelayId,
    required String remoteRelayId,
    required BigInt durationMs,
  }) = RsRelayAnywhereEvent_Completed;

  /// `stage` names the exact failing operation (bind / connect / accept / …)
  /// so a failure never has to be guessed from the category alone.
  const factory RsRelayAnywhereEvent.failed({
    required String message,
    required String category,
    String? stage,
  }) = RsRelayAnywhereEvent_Failed;
  const factory RsRelayAnywhereEvent.cancelled() = RsRelayAnywhereEvent_Cancelled;
}

/// One outbound file. Android passes a SAF descriptor; desktop passes a path.
class RsRelayAnywhereFile {
  final String? path;
  final int? fileDescriptor;

  /// Bounded inline text/share content. Picker and folder selections retain
  /// their path or Android SAF descriptor streaming source.
  final Uint8List? bytes;
  final String name;
  final BigInt size;
  final String fileType;
  final String? sha256;
  final String? preview;
  final String? lastModified;
  final String? lastAccessed;

  const RsRelayAnywhereFile({
    this.path,
    this.fileDescriptor,
    this.bytes,
    required this.name,
    required this.size,
    required this.fileType,
    this.sha256,
    this.preview,
    this.lastModified,
    this.lastAccessed,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      fileDescriptor.hashCode ^
      bytes.hashCode ^
      name.hashCode ^
      size.hashCode ^
      fileType.hashCode ^
      sha256.hashCode ^
      preview.hashCode ^
      lastModified.hashCode ^
      lastAccessed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsRelayAnywhereFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          fileDescriptor == other.fileDescriptor &&
          bytes == other.bytes &&
          name == other.name &&
          size == other.size &&
          fileType == other.fileType &&
          sha256 == other.sha256 &&
          preview == other.preview &&
          lastModified == other.lastModified &&
          lastAccessed == other.lastAccessed;
}

@freezed
sealed class RsRelayAnywhereListenerEvent with _$RsRelayAnywhereListenerEvent {
  const RsRelayAnywhereListenerEvent._();

  const factory RsRelayAnywhereListenerEvent.addressReady({
    required String address,
    required String localRelayId,
  }) = RsRelayAnywhereListenerEvent_AddressReady;
  const factory RsRelayAnywhereListenerEvent.sessionStarting({
    required BigInt sessionId,
  }) = RsRelayAnywhereListenerEvent_SessionStarting;
  const factory RsRelayAnywhereListenerEvent.sessionWaitingForPeer({
    required BigInt sessionId,
  }) = RsRelayAnywhereListenerEvent_SessionWaitingForPeer;
  const factory RsRelayAnywhereListenerEvent.sessionPeerConnected({
    required BigInt sessionId,
  }) = RsRelayAnywhereListenerEvent_SessionPeerConnected;
  const factory RsRelayAnywhereListenerEvent.sessionTlsEstablished({
    required BigInt sessionId,
  }) = RsRelayAnywhereListenerEvent_SessionTlsEstablished;
  const factory RsRelayAnywhereListenerEvent.sessionPeerAuthenticated({
    required BigInt sessionId,
    required String remoteRelayId,
  }) = RsRelayAnywhereListenerEvent_SessionPeerAuthenticated;
  const factory RsRelayAnywhereListenerEvent.sessionIncomingBatch({
    required BigInt sessionId,
    required BigInt transferId,
    required List<RsRelayIncomingFile> files,
    required String remoteRelayId,
  }) = RsRelayAnywhereListenerEvent_SessionIncomingBatch;
  const factory RsRelayAnywhereListenerEvent.sessionTransferring({
    required BigInt sessionId,
    required BigInt bytes,
    required BigInt total,
  }) = RsRelayAnywhereListenerEvent_SessionTransferring;
  const factory RsRelayAnywhereListenerEvent.sessionCompleted({
    required BigInt sessionId,
    required String path,
    required BigInt bytes,
    required String localRelayId,
    required String remoteRelayId,
    required BigInt durationMs,
  }) = RsRelayAnywhereListenerEvent_SessionCompleted;
  const factory RsRelayAnywhereListenerEvent.sessionCancelled({
    required BigInt sessionId,
  }) = RsRelayAnywhereListenerEvent_SessionCancelled;
  const factory RsRelayAnywhereListenerEvent.sessionFailed({
    required BigInt sessionId,
    required String message,
    required String category,
    String? stage,
  }) = RsRelayAnywhereListenerEvent_SessionFailed;
  const factory RsRelayAnywhereListenerEvent.stopped() = RsRelayAnywhereListenerEvent_Stopped;
}

class RsRelayIncomingFile {
  final String id;
  final String name;
  final BigInt size;
  final String fileType;
  final String? sha256;

  const RsRelayIncomingFile({
    required this.id,
    required this.name,
    required this.size,
    required this.fileType,
    this.sha256,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ size.hashCode ^ fileType.hashCode ^ sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsRelayIncomingFile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          size == other.size &&
          fileType == other.fileType &&
          sha256 == other.sha256;
}

enum RsRelayPathPreference {
  auto,
  forceDirect,
  forceRelay,
}
