// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:localsend_isolates/rust/frb_generated.dart';

part 'relay_anywhere.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `anywhere_runtime`, `file_spec`, `finish`, `map_event`, `map_failure`, `session_cancellation`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Parses a Relay address bundle. Fail-closed; never panics on bad input.
RsRelayAddress relayAnywhereParseAddress({required String address}) =>
    RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereParseAddress(address: address);

/// Opens a session handle. Any number may be open at once.
BigInt relayAnywhereOpenSession() => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereOpenSession();

/// Cancels exactly one session. Other sessions are unaffected.
bool relayAnywhereCancel({required BigInt sessionId}) => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereCancel(sessionId: sessionId);

/// Drops one session handle after it finished.
bool relayAnywhereCloseSession({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereCloseSession(sessionId: sessionId);

int relayAnywhereOpenSessionCount() => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereOpenSessionCount();

/// Answers one specific inbound request.
///
/// Accepting is session-scoped consent for this transfer only; it never becomes
/// persistent trust.
void relayAnywhereRespond({required BigInt sessionId, required BigInt transferId, required bool accept, String? targetsJson}) => RustLib.instance.api
    .crateApiRelayAnywhereRelayAnywhereRespond(sessionId: sessionId, transferId: transferId, accept: accept, targetsJson: targetsJson);

/// Receives one authenticated Anywhere transfer on `session_id`.
///
/// `private_key_pem` is the persisted Relay identity key from the platform
/// secret store. It is zeroed inside Rust before this call returns.
Stream<RsRelayAnywhereEvent> relayAnywhereReceive({
  required BigInt sessionId,
  required List<int> privateKeyPem,
  required String relayId,
  required String alias,
  required RsRelayPathPreference pathPreference,
  String? expectedRemoteRelayId,
}) => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereReceive(
  sessionId: sessionId,
  privateKeyPem: privateKeyPem,
  relayId: relayId,
  alias: alias,
  pathPreference: pathPreference,
  expectedRemoteRelayId: expectedRemoteRelayId,
);

/// Sends one authenticated Anywhere batch on `session_id`.
Stream<RsRelayAnywhereEvent> relayAnywhereSend({
  required BigInt sessionId,
  required List<int> privateKeyPem,
  required String relayId,
  required String address,
  required String alias,
  required RsRelayPathPreference pathPreference,
  required List<RsRelayAnywhereFile> files,
}) => RustLib.instance.api.crateApiRelayAnywhereRelayAnywhereSend(
  sessionId: sessionId,
  privateKeyPem: privateKeyPem,
  relayId: relayId,
  address: address,
  alias: alias,
  pathPreference: pathPreference,
  files: files,
);

/// A parsed Relay address. `claimedRelayId` is a claim to be proven by the
/// session, never evidence of identity or trust.
class RsRelayAddress {
  final int version;
  final String claimedRelayId;
  final bool routingAvailable;

  const RsRelayAddress({
    required this.version,
    required this.claimedRelayId,
    required this.routingAvailable,
  });

  @override
  int get hashCode => version.hashCode ^ claimedRelayId.hashCode ^ routingAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsRelayAddress &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          claimedRelayId == other.claimedRelayId &&
          routingAvailable == other.routingAvailable;
}

@freezed
sealed class RsRelayAnywhereEvent with _$RsRelayAnywhereEvent {
  const RsRelayAnywhereEvent._();

  const factory RsRelayAnywhereEvent.starting() = RsRelayAnywhereEvent_Starting;
  const factory RsRelayAnywhereEvent.addressReady({
    required String address,
    required String localRelayId,
  }) = RsRelayAnywhereEvent_AddressReady;
  const factory RsRelayAnywhereEvent.waitingForPeer() = RsRelayAnywhereEvent_WaitingForPeer;
  const factory RsRelayAnywhereEvent.connecting() = RsRelayAnywhereEvent_Connecting;
  const factory RsRelayAnywhereEvent.peerConnected() = RsRelayAnywhereEvent_PeerConnected;
  const factory RsRelayAnywhereEvent.tlsEstablished() = RsRelayAnywhereEvent_TlsEstablished;
  const factory RsRelayAnywhereEvent.peerAuthenticated({
    required String remoteRelayId,
  }) = RsRelayAnywhereEvent_PeerAuthenticated;
  const factory RsRelayAnywhereEvent.incomingBatch({
    required BigInt transferId,
    required List<RsRelayIncomingFile> files,
    required String remoteRelayId,
  }) = RsRelayAnywhereEvent_IncomingBatch;
  const factory RsRelayAnywhereEvent.transferring({
    required BigInt bytes,
    required BigInt total,
  }) = RsRelayAnywhereEvent_Transferring;
  const factory RsRelayAnywhereEvent.completed({
    required String path,
    required BigInt bytes,
    required String localRelayId,
    required String remoteRelayId,
    required BigInt durationMs,
  }) = RsRelayAnywhereEvent_Completed;

  /// `stage` names the exact failing operation (bind / connect / accept / …)
  /// so a failure never has to be guessed from the category alone.
  const factory RsRelayAnywhereEvent.failed({
    required String message,
    required String category,
    String? stage,
  }) = RsRelayAnywhereEvent_Failed;
  const factory RsRelayAnywhereEvent.cancelled() = RsRelayAnywhereEvent_Cancelled;
}

/// One outbound file. Android passes a SAF descriptor; desktop passes a path.
class RsRelayAnywhereFile {
  final String? path;
  final int? fileDescriptor;
  final String name;
  final BigInt size;
  final String fileType;
  final String? sha256;

  const RsRelayAnywhereFile({
    this.path,
    this.fileDescriptor,
    required this.name,
    required this.size,
    required this.fileType,
    this.sha256,
  });

  @override
  int get hashCode => path.hashCode ^ fileDescriptor.hashCode ^ name.hashCode ^ size.hashCode ^ fileType.hashCode ^ sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsRelayAnywhereFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          fileDescriptor == other.fileDescriptor &&
          name == other.name &&
          size == other.size &&
          fileType == other.fileType &&
          sha256 == other.sha256;
}

class RsRelayIncomingFile {
  final String id;
  final String name;
  final BigInt size;

  const RsRelayIncomingFile({
    required this.id,
    required this.name,
    required this.size,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsRelayIncomingFile && runtimeType == other.runtimeType && id == other.id && name == other.name && size == other.size;
}

enum RsRelayPathPreference {
  auto,
  forceDirect,
  forceRelay,
}
