// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:localsend_isolates/rust/api/cancel.dart';
import 'package:localsend_isolates/rust/api/http.dart';
import 'package:localsend_isolates/rust/api/model.dart';
import 'package:localsend_isolates/rust/frb_generated.dart';

part 'relay_transfer.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `canonical_error_category`, `map_event`, `origin_label`, `relay_transfer_file`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Runs one LAN transfer through the canonical engine using the caller-owned
/// certificate-pinned client.  The client is never recreated, so a prior
/// verified Relay proof and the file bytes share the same TLS pin.
Stream<RsRelayTransferEvent> relayTransferSendLan({
  required RsHttpClient client,
  required ProtocolType protocol,
  required String ip,
  required int port,
  required String transferId,
  required RegisterDto info,
  required List<RsRelayTransferFile> files,
  String? pin,
  required RsCancellationToken cancelToken,
}) => RustLib.instance.api.crateApiRelayTransferRelayTransferSendLan(
  client: client,
  protocol: protocol,
  ip: ip,
  port: port,
  transferId: transferId,
  info: info,
  files: files,
  pin: pin,
  cancelToken: cancelToken,
);

@freezed
sealed class RsRelayTransferEvent with _$RsRelayTransferEvent {
  const RsRelayTransferEvent._();

  const factory RsRelayTransferEvent.outgoingStarted({
    required String transferId,
    required BigInt totalBytes,
    required String origin,
  }) = RsRelayTransferEvent_OutgoingStarted;
  const factory RsRelayTransferEvent.accepted({
    required String transferId,
    required String sessionId,
    required List<String> acceptedFileIds,
    required BigInt totalBytes,
    required String origin,
  }) = RsRelayTransferEvent_Accepted;
  const factory RsRelayTransferEvent.declined({
    required String transferId,
    String? fileId,
    required String origin,
  }) = RsRelayTransferEvent_Declined;
  const factory RsRelayTransferEvent.fileStarted({
    required String transferId,
    required String sessionId,
    required String fileId,
    required String fileName,
    required int fileIndex,
    required int fileCount,
    required BigInt totalBytes,
    required String origin,
  }) = RsRelayTransferEvent_FileStarted;
  const factory RsRelayTransferEvent.fileProgress({
    required String transferId,
    required String sessionId,
    required String fileId,
    required BigInt bytes,
    required BigInt totalBytes,
    required String origin,
  }) = RsRelayTransferEvent_FileProgress;
  const factory RsRelayTransferEvent.overallProgress({
    required String transferId,
    required String sessionId,
    required BigInt bytes,
    required BigInt totalBytes,
    required String origin,
  }) = RsRelayTransferEvent_OverallProgress;
  const factory RsRelayTransferEvent.completed({
    required String transferId,
    String? sessionId,
    required BigInt bytes,
    required String origin,
  }) = RsRelayTransferEvent_Completed;
  const factory RsRelayTransferEvent.failed({
    required String transferId,
    required String category,
  }) = RsRelayTransferEvent_Failed;
  const factory RsRelayTransferEvent.cancelled({
    required String transferId,
  }) = RsRelayTransferEvent_Cancelled;
}

/// One UI-selected file passed into the canonical engine.
class RsRelayTransferFile {
  final FileDto file;
  final String? path;
  final int? fileDescriptor;
  final Uint8List? bytes;

  const RsRelayTransferFile({
    required this.file,
    this.path,
    this.fileDescriptor,
    this.bytes,
  });

  @override
  int get hashCode => file.hashCode ^ path.hashCode ^ fileDescriptor.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsRelayTransferFile &&
          runtimeType == other.runtimeType &&
          file == other.file &&
          path == other.path &&
          fileDescriptor == other.fileDescriptor &&
          bytes == other.bytes;
}
