// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'package:relay_isolates/rust/api/cancel.dart';
import 'package:relay_isolates/rust/api/continuity.dart';
import 'package:relay_isolates/rust/api/crypto.dart';
import 'package:relay_isolates/rust/api/discovery.dart';
import 'package:relay_isolates/rust/api/filename.dart';
import 'package:relay_isolates/rust/api/http.dart';
import 'package:relay_isolates/rust/api/kdeconnect.dart';
import 'package:relay_isolates/rust/api/logging.dart';
import 'package:relay_isolates/rust/api/metadata.dart';
import 'package:relay_isolates/rust/api/model.dart';
import 'package:relay_isolates/rust/api/relay_anywhere.dart';
import 'package:relay_isolates/rust/api/relay_transfer.dart';
import 'package:relay_isolates/rust/api/server.dart';
import 'package:relay_isolates/rust/api/stream.dart';
import 'package:relay_isolates/rust/api/webrtc.dart';
import 'package:relay_isolates/rust/frb_generated.dart';
import 'package:uuid/uuid.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_Dart2RustStreamReceiverPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiverPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_Dart2RustStreamSinkPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSinkPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LsSignalingConnectionPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnectionPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RtcFileReceiverPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiverPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RtcFileSenderPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSenderPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RtcReceiveControllerPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveControllerPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RtcSendControllerPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendControllerPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RsCancellationTokenPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationTokenPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RsDiscoveryPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscoveryPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RsHttpClientPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClientPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RsHttpServerPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServerPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RsKdeConnectPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnectPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Dart2RustStreamReceiver dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(dynamic raw);

  @protected
  Dart2RustStreamSink dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(dynamic raw);

  @protected
  LsSignalingConnection dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection(dynamic raw);

  @protected
  RtcFileReceiver dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver(dynamic raw);

  @protected
  RtcFileSender dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender(dynamic raw);

  @protected
  RtcReceiveController dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController(dynamic raw);

  @protected
  RtcSendController dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(dynamic raw);

  @protected
  RsCancellationToken dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken(dynamic raw);

  @protected
  RsDiscovery dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery(dynamic raw);

  @protected
  RsHttpClient dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(dynamic raw);

  @protected
  RsHttpServer dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer(dynamic raw);

  @protected
  RsKdeConnect dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect(dynamic raw);

  @protected
  Dart2RustStreamSink dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(dynamic raw);

  @protected
  RtcSendController dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(dynamic raw);

  @protected
  LsSignalingConnection dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection(dynamic raw);

  @protected
  RtcFileReceiver dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver(dynamic raw);

  @protected
  RtcFileSender dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender(dynamic raw);

  @protected
  RtcReceiveController dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController(dynamic raw);

  @protected
  RtcSendController dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(dynamic raw);

  @protected
  RsCancellationToken dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken(dynamic raw);

  @protected
  RsDiscovery dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery(dynamic raw);

  @protected
  RsHttpClient dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(dynamic raw);

  @protected
  RsHttpServer dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer(dynamic raw);

  @protected
  RsKdeConnect dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect(dynamic raw);

  @protected
  FutureOr<void> Function(LsSignalingConnection)
  dco_decode_DartFn_Inputs_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, FileDto> dco_decode_Map_String_file_dto_None(dynamic raw);

  @protected
  Dart2RustStreamReceiver dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(dynamic raw);

  @protected
  Dart2RustStreamSink dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(dynamic raw);

  @protected
  LsSignalingConnection dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection(dynamic raw);

  @protected
  RtcFileReceiver dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver(dynamic raw);

  @protected
  RtcFileSender dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender(dynamic raw);

  @protected
  RtcReceiveController dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController(dynamic raw);

  @protected
  RtcSendController dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(dynamic raw);

  @protected
  RsCancellationToken dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken(dynamic raw);

  @protected
  RsDiscovery dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery(dynamic raw);

  @protected
  RsHttpClient dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(dynamic raw);

  @protected
  RsHttpServer dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer(dynamic raw);

  @protected
  RsKdeConnect dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect(dynamic raw);

  @protected
  Set<String> dco_decode_Set_String_None(dynamic raw);

  @protected
  RustStreamSink<RtcFileReceiver> dco_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<double> dco_decode_StreamSink_f_64_Sse(dynamic raw);

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(dynamic raw);

  @protected
  RustStreamSink<RsContinuityEvent> dco_decode_StreamSink_rs_continuity_event_Sse(dynamic raw);

  @protected
  RustStreamSink<RsContinuityHostRequest> dco_decode_StreamSink_rs_continuity_host_request_Sse(dynamic raw);

  @protected
  RustStreamSink<RsHashFileEvent> dco_decode_StreamSink_rs_hash_file_event_Sse(dynamic raw);

  @protected
  RustStreamSink<RsKdeConnectEvent> dco_decode_StreamSink_rs_kde_connect_event_Sse(dynamic raw);

  @protected
  RustStreamSink<RsRelayAnywhereEvent> dco_decode_StreamSink_rs_relay_anywhere_event_Sse(dynamic raw);

  @protected
  RustStreamSink<RsRelayAnywhereListenerEvent> dco_decode_StreamSink_rs_relay_anywhere_listener_event_Sse(dynamic raw);

  @protected
  RustStreamSink<RsRelayLanPairingEvent> dco_decode_StreamSink_rs_relay_lan_pairing_event_Sse(dynamic raw);

  @protected
  RustStreamSink<RsRelayTransferEvent> dco_decode_StreamSink_rs_relay_transfer_event_Sse(dynamic raw);

  @protected
  RustStreamSink<RsServerEvent> dco_decode_StreamSink_rs_server_event_Sse(dynamic raw);

  @protected
  RustStreamSink<RsStoredDevice> dco_decode_StreamSink_rs_stored_device_Sse(dynamic raw);

  @protected
  RustStreamSink<RsUploadEvent> dco_decode_StreamSink_rs_upload_event_Sse(dynamic raw);

  @protected
  RustStreamSink<RTCFileError> dco_decode_StreamSink_rtc_file_error_Sse(dynamic raw);

  @protected
  RustStreamSink<RTCStatus> dco_decode_StreamSink_rtc_status_Sse(dynamic raw);

  @protected
  RustStreamSink<WsServerMessage> dco_decode_StreamSink_ws_server_message_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  UuidValue dco_decode_Uuid(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Dart2RustStreamReceiver dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    dynamic raw,
  );

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ClientInfo dco_decode_box_autoadd_client_info(dynamic raw);

  @protected
  ClientInfoWithoutId dco_decode_box_autoadd_client_info_without_id(dynamic raw);

  @protected
  DeviceType dco_decode_box_autoadd_device_type(dynamic raw);

  @protected
  ExpectingPublicKey dco_decode_box_autoadd_expecting_public_key(dynamic raw);

  @protected
  FileDto dco_decode_box_autoadd_file_dto(dynamic raw);

  @protected
  FileMetadata dco_decode_box_autoadd_file_metadata(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  PinConfig dco_decode_box_autoadd_pin_config(dynamic raw);

  @protected
  PrepareUploadRequestDto dco_decode_box_autoadd_prepare_upload_request_dto(dynamic raw);

  @protected
  PrepareUploadResponseDto dco_decode_box_autoadd_prepare_upload_response_dto(dynamic raw);

  @protected
  ProposingClientInfo dco_decode_box_autoadd_proposing_client_info(dynamic raw);

  @protected
  RegisterDto dco_decode_box_autoadd_register_dto(dynamic raw);

  @protected
  RegisterDtoV2 dco_decode_box_autoadd_register_dto_v_2(dynamic raw);

  @protected
  RsCallState dco_decode_box_autoadd_rs_call_state(dynamic raw);

  @protected
  RsCapabilityManifest dco_decode_box_autoadd_rs_capability_manifest(dynamic raw);

  @protected
  RsDiscoveredDevice dco_decode_box_autoadd_rs_discovered_device(dynamic raw);

  @protected
  RsHttpClientError dco_decode_box_autoadd_rs_http_client_error(dynamic raw);

  @protected
  RsKdeConnectIdentity dco_decode_box_autoadd_rs_kde_connect_identity(dynamic raw);

  @protected
  RsKdeSmsMessage dco_decode_box_autoadd_rs_kde_sms_message(dynamic raw);

  @protected
  RsKdeTelephonyEvent dco_decode_box_autoadd_rs_kde_telephony_event(dynamic raw);

  @protected
  RsSmsMessage dco_decode_box_autoadd_rs_sms_message(dynamic raw);

  @protected
  RTCSendFileResponse dco_decode_box_autoadd_rtc_send_file_response(dynamic raw);

  @protected
  TlsConfig dco_decode_box_autoadd_tls_config(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  WebParams dco_decode_box_autoadd_web_params(dynamic raw);

  @protected
  WebSendParams dco_decode_box_autoadd_web_send_params(dynamic raw);

  @protected
  WsServerSdpMessage dco_decode_box_autoadd_ws_server_sdp_message(dynamic raw);

  @protected
  ClientInfo dco_decode_client_info(dynamic raw);

  @protected
  ClientInfoWithoutId dco_decode_client_info_without_id(dynamic raw);

  @protected
  DeviceLogKind dco_decode_device_log_kind(dynamic raw);

  @protected
  DeviceType dco_decode_device_type(dynamic raw);

  @protected
  ExpectingPublicKey dco_decode_expecting_public_key(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FileDto dco_decode_file_dto(dynamic raw);

  @protected
  FileMetadata dco_decode_file_metadata(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  KeyPair dco_decode_key_pair(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ClientInfo> dco_decode_list_client_info(dynamic raw);

  @protected
  List<FileDto> dco_decode_list_file_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, FileDto)> dco_decode_list_record_string_file_dto(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<RsCapabilityEntry> dco_decode_list_rs_capability_entry(dynamic raw);

  @protected
  List<RsDeviceChannel> dco_decode_list_rs_device_channel(dynamic raw);

  @protected
  List<RsDeviceLog> dco_decode_list_rs_device_log(dynamic raw);

  @protected
  List<RsKdeConnectDevice> dco_decode_list_rs_kde_connect_device(dynamic raw);

  @protected
  List<RsKdeConnectTrustedDevice> dco_decode_list_rs_kde_connect_trusted_device(dynamic raw);

  @protected
  List<RsKdeNotification> dco_decode_list_rs_kde_notification(dynamic raw);

  @protected
  List<RsKdeSmsAttachment> dco_decode_list_rs_kde_sms_attachment(dynamic raw);

  @protected
  List<RsKdeSmsConversation> dco_decode_list_rs_kde_sms_conversation(dynamic raw);

  @protected
  List<RsKdeSmsMessage> dco_decode_list_rs_kde_sms_message(dynamic raw);

  @protected
  List<RsLanCandidate> dco_decode_list_rs_lan_candidate(dynamic raw);

  @protected
  List<RsRelayAnywhereFile> dco_decode_list_rs_relay_anywhere_file(dynamic raw);

  @protected
  List<RsRelayIncomingFile> dco_decode_list_rs_relay_incoming_file(dynamic raw);

  @protected
  List<RsRelayTransferFile> dco_decode_list_rs_relay_transfer_file(dynamic raw);

  @protected
  List<RsSmsConversation> dco_decode_list_rs_sms_conversation(dynamic raw);

  @protected
  List<RsSmsMessage> dco_decode_list_rs_sms_message(dynamic raw);

  @protected
  LsHttpClientVersion dco_decode_ls_http_client_version(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Dart2RustStreamReceiver?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  DeviceType? dco_decode_opt_box_autoadd_device_type(dynamic raw);

  @protected
  ExpectingPublicKey? dco_decode_opt_box_autoadd_expecting_public_key(dynamic raw);

  @protected
  FileMetadata? dco_decode_opt_box_autoadd_file_metadata(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  PinConfig? dco_decode_opt_box_autoadd_pin_config(dynamic raw);

  @protected
  PrepareUploadResponseDto? dco_decode_opt_box_autoadd_prepare_upload_response_dto(dynamic raw);

  @protected
  RsKdeSmsMessage? dco_decode_opt_box_autoadd_rs_kde_sms_message(dynamic raw);

  @protected
  TlsConfig? dco_decode_opt_box_autoadd_tls_config(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  WebParams? dco_decode_opt_box_autoadd_web_params(dynamic raw);

  @protected
  WebSendParams? dco_decode_opt_box_autoadd_web_send_params(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PinConfig dco_decode_pin_config(dynamic raw);

  @protected
  PrepareUploadRequestDto dco_decode_prepare_upload_request_dto(dynamic raw);

  @protected
  PrepareUploadResponseDto dco_decode_prepare_upload_response_dto(dynamic raw);

  @protected
  PrepareUploadResult dco_decode_prepare_upload_result(dynamic raw);

  @protected
  ProposingClientInfo dco_decode_proposing_client_info(dynamic raw);

  @protected
  ProtocolType dco_decode_protocol_type(dynamic raw);

  @protected
  (Dart2RustStreamSink, Dart2RustStreamReceiver)
  dco_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dart_2_rust_stream_sink_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dart_2_rust_stream_receiver(
    dynamic raw,
  );

  @protected
  (String, FileDto) dco_decode_record_string_file_dto(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  RegisterDto dco_decode_register_dto(dynamic raw);

  @protected
  RegisterDtoV2 dco_decode_register_dto_v_2(dynamic raw);

  @protected
  RegisterResponseDto dco_decode_register_response_dto(dynamic raw);

  @protected
  RelayIdentityMaterial dco_decode_relay_identity_material(dynamic raw);

  @protected
  ResultWithPublicKeyRegisterResponseDto dco_decode_result_with_public_key_register_response_dto(dynamic raw);

  @protected
  RsCallAction dco_decode_rs_call_action(dynamic raw);

  @protected
  RsCallPhase dco_decode_rs_call_phase(dynamic raw);

  @protected
  RsCallState dco_decode_rs_call_state(dynamic raw);

  @protected
  RsCapabilityEntry dco_decode_rs_capability_entry(dynamic raw);

  @protected
  RsCapabilityManifest dco_decode_rs_capability_manifest(dynamic raw);

  @protected
  RsCapabilityState dco_decode_rs_capability_state(dynamic raw);

  @protected
  RsChargingState dco_decode_rs_charging_state(dynamic raw);

  @protected
  RsClipboardMode dco_decode_rs_clipboard_mode(dynamic raw);

  @protected
  RsContinuityCapability dco_decode_rs_continuity_capability(dynamic raw);

  @protected
  RsContinuityEvent dco_decode_rs_continuity_event(dynamic raw);

  @protected
  RsContinuityHostRequest dco_decode_rs_continuity_host_request(dynamic raw);

  @protected
  RsDeviceChannel dco_decode_rs_device_channel(dynamic raw);

  @protected
  RsDeviceLog dco_decode_rs_device_log(dynamic raw);

  @protected
  RsDiscoveredDevice dco_decode_rs_discovered_device(dynamic raw);

  @protected
  RsHashFileEvent dco_decode_rs_hash_file_event(dynamic raw);

  @protected
  RsHttpClientError dco_decode_rs_http_client_error(dynamic raw);

  @protected
  RsKdeConnectDevice dco_decode_rs_kde_connect_device(dynamic raw);

  @protected
  RsKdeConnectEvent dco_decode_rs_kde_connect_event(dynamic raw);

  @protected
  RsKdeConnectIdentity dco_decode_rs_kde_connect_identity(dynamic raw);

  @protected
  RsKdeConnectTrustedDevice dco_decode_rs_kde_connect_trusted_device(dynamic raw);

  @protected
  RsKdeNotification dco_decode_rs_kde_notification(dynamic raw);

  @protected
  RsKdeSmsAttachment dco_decode_rs_kde_sms_attachment(dynamic raw);

  @protected
  RsKdeSmsConversation dco_decode_rs_kde_sms_conversation(dynamic raw);

  @protected
  RsKdeSmsMessage dco_decode_rs_kde_sms_message(dynamic raw);

  @protected
  RsKdeTelephonyEvent dco_decode_rs_kde_telephony_event(dynamic raw);

  @protected
  RsLanCandidate dco_decode_rs_lan_candidate(dynamic raw);

  @protected
  RsRelayAddress dco_decode_rs_relay_address(dynamic raw);

  @protected
  RsRelayAnywhereEvent dco_decode_rs_relay_anywhere_event(dynamic raw);

  @protected
  RsRelayAnywhereFile dco_decode_rs_relay_anywhere_file(dynamic raw);

  @protected
  RsRelayAnywhereListenerEvent dco_decode_rs_relay_anywhere_listener_event(dynamic raw);

  @protected
  RsRelayIncomingFile dco_decode_rs_relay_incoming_file(dynamic raw);

  @protected
  RsRelayLanPairingEvent dco_decode_rs_relay_lan_pairing_event(dynamic raw);

  @protected
  RsRelayPathPreference dco_decode_rs_relay_path_preference(dynamic raw);

  @protected
  RsRelayPeerAuth dco_decode_rs_relay_peer_auth(dynamic raw);

  @protected
  RsRelayTransferEvent dco_decode_rs_relay_transfer_event(dynamic raw);

  @protected
  RsRelayTransferFile dco_decode_rs_relay_transfer_file(dynamic raw);

  @protected
  RsServerEvent dco_decode_rs_server_event(dynamic raw);

  @protected
  RsSmsConversation dco_decode_rs_sms_conversation(dynamic raw);

  @protected
  RsSmsMessage dco_decode_rs_sms_message(dynamic raw);

  @protected
  RsStoredDevice dco_decode_rs_stored_device(dynamic raw);

  @protected
  RsUploadEvent dco_decode_rs_upload_event(dynamic raw);

  @protected
  RTCFileError dco_decode_rtc_file_error(dynamic raw);

  @protected
  RTCSendFileResponse dco_decode_rtc_send_file_response(dynamic raw);

  @protected
  RTCStatus dco_decode_rtc_status(dynamic raw);

  @protected
  SecurityContext dco_decode_security_context(dynamic raw);

  @protected
  SessionEndReasonV2 dco_decode_session_end_reason_v_2(dynamic raw);

  @protected
  TlsConfig dco_decode_tls_config(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WebI18n dco_decode_web_i_18_n(dynamic raw);

  @protected
  WebParams dco_decode_web_params(dynamic raw);

  @protected
  WebSendParams dco_decode_web_send_params(dynamic raw);

  @protected
  WsServerMessage dco_decode_ws_server_message(dynamic raw);

  @protected
  WsServerSdpMessage dco_decode_ws_server_sdp_message(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Dart2RustStreamReceiver sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    SseDeserializer deserializer,
  );

  @protected
  Dart2RustStreamSink sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    SseDeserializer deserializer,
  );

  @protected
  LsSignalingConnection sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection(
    SseDeserializer deserializer,
  );

  @protected
  RtcFileReceiver sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver(SseDeserializer deserializer);

  @protected
  RtcFileSender sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender(SseDeserializer deserializer);

  @protected
  RtcReceiveController sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController(
    SseDeserializer deserializer,
  );

  @protected
  RtcSendController sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(
    SseDeserializer deserializer,
  );

  @protected
  RsCancellationToken sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken(
    SseDeserializer deserializer,
  );

  @protected
  RsDiscovery sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery(SseDeserializer deserializer);

  @protected
  RsHttpClient sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(SseDeserializer deserializer);

  @protected
  RsHttpServer sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer(SseDeserializer deserializer);

  @protected
  RsKdeConnect sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect(SseDeserializer deserializer);

  @protected
  Dart2RustStreamSink sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    SseDeserializer deserializer,
  );

  @protected
  RtcSendController sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(
    SseDeserializer deserializer,
  );

  @protected
  LsSignalingConnection sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection(
    SseDeserializer deserializer,
  );

  @protected
  RtcFileReceiver sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver(SseDeserializer deserializer);

  @protected
  RtcFileSender sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender(SseDeserializer deserializer);

  @protected
  RtcReceiveController sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController(
    SseDeserializer deserializer,
  );

  @protected
  RtcSendController sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(SseDeserializer deserializer);

  @protected
  RsCancellationToken sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken(
    SseDeserializer deserializer,
  );

  @protected
  RsDiscovery sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery(SseDeserializer deserializer);

  @protected
  RsHttpClient sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(SseDeserializer deserializer);

  @protected
  RsHttpServer sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer(SseDeserializer deserializer);

  @protected
  RsKdeConnect sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect(SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(SseDeserializer deserializer);

  @protected
  Map<String, FileDto> sse_decode_Map_String_file_dto_None(SseDeserializer deserializer);

  @protected
  Dart2RustStreamReceiver sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    SseDeserializer deserializer,
  );

  @protected
  Dart2RustStreamSink sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(SseDeserializer deserializer);

  @protected
  LsSignalingConnection sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection(SseDeserializer deserializer);

  @protected
  RtcFileReceiver sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver(SseDeserializer deserializer);

  @protected
  RtcFileSender sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender(SseDeserializer deserializer);

  @protected
  RtcReceiveController sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController(SseDeserializer deserializer);

  @protected
  RtcSendController sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(SseDeserializer deserializer);

  @protected
  RsCancellationToken sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken(SseDeserializer deserializer);

  @protected
  RsDiscovery sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery(SseDeserializer deserializer);

  @protected
  RsHttpClient sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(SseDeserializer deserializer);

  @protected
  RsHttpServer sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer(SseDeserializer deserializer);

  @protected
  RsKdeConnect sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect(SseDeserializer deserializer);

  @protected
  Set<String> sse_decode_Set_String_None(SseDeserializer deserializer);

  @protected
  RustStreamSink<RtcFileReceiver> sse_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<double> sse_decode_StreamSink_f_64_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<RsContinuityEvent> sse_decode_StreamSink_rs_continuity_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<RsContinuityHostRequest> sse_decode_StreamSink_rs_continuity_host_request_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<RsHashFileEvent> sse_decode_StreamSink_rs_hash_file_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<RsKdeConnectEvent> sse_decode_StreamSink_rs_kde_connect_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<RsRelayAnywhereEvent> sse_decode_StreamSink_rs_relay_anywhere_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<RsRelayAnywhereListenerEvent> sse_decode_StreamSink_rs_relay_anywhere_listener_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<RsRelayLanPairingEvent> sse_decode_StreamSink_rs_relay_lan_pairing_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<RsRelayTransferEvent> sse_decode_StreamSink_rs_relay_transfer_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<RsServerEvent> sse_decode_StreamSink_rs_server_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<RsStoredDevice> sse_decode_StreamSink_rs_stored_device_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<RsUploadEvent> sse_decode_StreamSink_rs_upload_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<RTCFileError> sse_decode_StreamSink_rtc_file_error_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<RTCStatus> sse_decode_StreamSink_rtc_status_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<WsServerMessage> sse_decode_StreamSink_ws_server_message_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Dart2RustStreamReceiver sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ClientInfo sse_decode_box_autoadd_client_info(SseDeserializer deserializer);

  @protected
  ClientInfoWithoutId sse_decode_box_autoadd_client_info_without_id(SseDeserializer deserializer);

  @protected
  DeviceType sse_decode_box_autoadd_device_type(SseDeserializer deserializer);

  @protected
  ExpectingPublicKey sse_decode_box_autoadd_expecting_public_key(SseDeserializer deserializer);

  @protected
  FileDto sse_decode_box_autoadd_file_dto(SseDeserializer deserializer);

  @protected
  FileMetadata sse_decode_box_autoadd_file_metadata(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  PinConfig sse_decode_box_autoadd_pin_config(SseDeserializer deserializer);

  @protected
  PrepareUploadRequestDto sse_decode_box_autoadd_prepare_upload_request_dto(SseDeserializer deserializer);

  @protected
  PrepareUploadResponseDto sse_decode_box_autoadd_prepare_upload_response_dto(SseDeserializer deserializer);

  @protected
  ProposingClientInfo sse_decode_box_autoadd_proposing_client_info(SseDeserializer deserializer);

  @protected
  RegisterDto sse_decode_box_autoadd_register_dto(SseDeserializer deserializer);

  @protected
  RegisterDtoV2 sse_decode_box_autoadd_register_dto_v_2(SseDeserializer deserializer);

  @protected
  RsCallState sse_decode_box_autoadd_rs_call_state(SseDeserializer deserializer);

  @protected
  RsCapabilityManifest sse_decode_box_autoadd_rs_capability_manifest(SseDeserializer deserializer);

  @protected
  RsDiscoveredDevice sse_decode_box_autoadd_rs_discovered_device(SseDeserializer deserializer);

  @protected
  RsHttpClientError sse_decode_box_autoadd_rs_http_client_error(SseDeserializer deserializer);

  @protected
  RsKdeConnectIdentity sse_decode_box_autoadd_rs_kde_connect_identity(SseDeserializer deserializer);

  @protected
  RsKdeSmsMessage sse_decode_box_autoadd_rs_kde_sms_message(SseDeserializer deserializer);

  @protected
  RsKdeTelephonyEvent sse_decode_box_autoadd_rs_kde_telephony_event(SseDeserializer deserializer);

  @protected
  RsSmsMessage sse_decode_box_autoadd_rs_sms_message(SseDeserializer deserializer);

  @protected
  RTCSendFileResponse sse_decode_box_autoadd_rtc_send_file_response(SseDeserializer deserializer);

  @protected
  TlsConfig sse_decode_box_autoadd_tls_config(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  WebParams sse_decode_box_autoadd_web_params(SseDeserializer deserializer);

  @protected
  WebSendParams sse_decode_box_autoadd_web_send_params(SseDeserializer deserializer);

  @protected
  WsServerSdpMessage sse_decode_box_autoadd_ws_server_sdp_message(SseDeserializer deserializer);

  @protected
  ClientInfo sse_decode_client_info(SseDeserializer deserializer);

  @protected
  ClientInfoWithoutId sse_decode_client_info_without_id(SseDeserializer deserializer);

  @protected
  DeviceLogKind sse_decode_device_log_kind(SseDeserializer deserializer);

  @protected
  DeviceType sse_decode_device_type(SseDeserializer deserializer);

  @protected
  ExpectingPublicKey sse_decode_expecting_public_key(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FileDto sse_decode_file_dto(SseDeserializer deserializer);

  @protected
  FileMetadata sse_decode_file_metadata(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  KeyPair sse_decode_key_pair(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ClientInfo> sse_decode_list_client_info(SseDeserializer deserializer);

  @protected
  List<FileDto> sse_decode_list_file_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, FileDto)> sse_decode_list_record_string_file_dto(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(SseDeserializer deserializer);

  @protected
  List<RsCapabilityEntry> sse_decode_list_rs_capability_entry(SseDeserializer deserializer);

  @protected
  List<RsDeviceChannel> sse_decode_list_rs_device_channel(SseDeserializer deserializer);

  @protected
  List<RsDeviceLog> sse_decode_list_rs_device_log(SseDeserializer deserializer);

  @protected
  List<RsKdeConnectDevice> sse_decode_list_rs_kde_connect_device(SseDeserializer deserializer);

  @protected
  List<RsKdeConnectTrustedDevice> sse_decode_list_rs_kde_connect_trusted_device(SseDeserializer deserializer);

  @protected
  List<RsKdeNotification> sse_decode_list_rs_kde_notification(SseDeserializer deserializer);

  @protected
  List<RsKdeSmsAttachment> sse_decode_list_rs_kde_sms_attachment(SseDeserializer deserializer);

  @protected
  List<RsKdeSmsConversation> sse_decode_list_rs_kde_sms_conversation(SseDeserializer deserializer);

  @protected
  List<RsKdeSmsMessage> sse_decode_list_rs_kde_sms_message(SseDeserializer deserializer);

  @protected
  List<RsLanCandidate> sse_decode_list_rs_lan_candidate(SseDeserializer deserializer);

  @protected
  List<RsRelayAnywhereFile> sse_decode_list_rs_relay_anywhere_file(SseDeserializer deserializer);

  @protected
  List<RsRelayIncomingFile> sse_decode_list_rs_relay_incoming_file(SseDeserializer deserializer);

  @protected
  List<RsRelayTransferFile> sse_decode_list_rs_relay_transfer_file(SseDeserializer deserializer);

  @protected
  List<RsSmsConversation> sse_decode_list_rs_sms_conversation(SseDeserializer deserializer);

  @protected
  List<RsSmsMessage> sse_decode_list_rs_sms_message(SseDeserializer deserializer);

  @protected
  LsHttpClientVersion sse_decode_ls_http_client_version(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Dart2RustStreamReceiver?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DeviceType? sse_decode_opt_box_autoadd_device_type(SseDeserializer deserializer);

  @protected
  ExpectingPublicKey? sse_decode_opt_box_autoadd_expecting_public_key(SseDeserializer deserializer);

  @protected
  FileMetadata? sse_decode_opt_box_autoadd_file_metadata(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  PinConfig? sse_decode_opt_box_autoadd_pin_config(SseDeserializer deserializer);

  @protected
  PrepareUploadResponseDto? sse_decode_opt_box_autoadd_prepare_upload_response_dto(SseDeserializer deserializer);

  @protected
  RsKdeSmsMessage? sse_decode_opt_box_autoadd_rs_kde_sms_message(SseDeserializer deserializer);

  @protected
  TlsConfig? sse_decode_opt_box_autoadd_tls_config(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  WebParams? sse_decode_opt_box_autoadd_web_params(SseDeserializer deserializer);

  @protected
  WebSendParams? sse_decode_opt_box_autoadd_web_send_params(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PinConfig sse_decode_pin_config(SseDeserializer deserializer);

  @protected
  PrepareUploadRequestDto sse_decode_prepare_upload_request_dto(SseDeserializer deserializer);

  @protected
  PrepareUploadResponseDto sse_decode_prepare_upload_response_dto(SseDeserializer deserializer);

  @protected
  PrepareUploadResult sse_decode_prepare_upload_result(SseDeserializer deserializer);

  @protected
  ProposingClientInfo sse_decode_proposing_client_info(SseDeserializer deserializer);

  @protected
  ProtocolType sse_decode_protocol_type(SseDeserializer deserializer);

  @protected
  (Dart2RustStreamSink, Dart2RustStreamReceiver)
  sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dart_2_rust_stream_sink_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dart_2_rust_stream_receiver(
    SseDeserializer deserializer,
  );

  @protected
  (String, FileDto) sse_decode_record_string_file_dto(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(SseDeserializer deserializer);

  @protected
  RegisterDto sse_decode_register_dto(SseDeserializer deserializer);

  @protected
  RegisterDtoV2 sse_decode_register_dto_v_2(SseDeserializer deserializer);

  @protected
  RegisterResponseDto sse_decode_register_response_dto(SseDeserializer deserializer);

  @protected
  RelayIdentityMaterial sse_decode_relay_identity_material(SseDeserializer deserializer);

  @protected
  ResultWithPublicKeyRegisterResponseDto sse_decode_result_with_public_key_register_response_dto(SseDeserializer deserializer);

  @protected
  RsCallAction sse_decode_rs_call_action(SseDeserializer deserializer);

  @protected
  RsCallPhase sse_decode_rs_call_phase(SseDeserializer deserializer);

  @protected
  RsCallState sse_decode_rs_call_state(SseDeserializer deserializer);

  @protected
  RsCapabilityEntry sse_decode_rs_capability_entry(SseDeserializer deserializer);

  @protected
  RsCapabilityManifest sse_decode_rs_capability_manifest(SseDeserializer deserializer);

  @protected
  RsCapabilityState sse_decode_rs_capability_state(SseDeserializer deserializer);

  @protected
  RsChargingState sse_decode_rs_charging_state(SseDeserializer deserializer);

  @protected
  RsClipboardMode sse_decode_rs_clipboard_mode(SseDeserializer deserializer);

  @protected
  RsContinuityCapability sse_decode_rs_continuity_capability(SseDeserializer deserializer);

  @protected
  RsContinuityEvent sse_decode_rs_continuity_event(SseDeserializer deserializer);

  @protected
  RsContinuityHostRequest sse_decode_rs_continuity_host_request(SseDeserializer deserializer);

  @protected
  RsDeviceChannel sse_decode_rs_device_channel(SseDeserializer deserializer);

  @protected
  RsDeviceLog sse_decode_rs_device_log(SseDeserializer deserializer);

  @protected
  RsDiscoveredDevice sse_decode_rs_discovered_device(SseDeserializer deserializer);

  @protected
  RsHashFileEvent sse_decode_rs_hash_file_event(SseDeserializer deserializer);

  @protected
  RsHttpClientError sse_decode_rs_http_client_error(SseDeserializer deserializer);

  @protected
  RsKdeConnectDevice sse_decode_rs_kde_connect_device(SseDeserializer deserializer);

  @protected
  RsKdeConnectEvent sse_decode_rs_kde_connect_event(SseDeserializer deserializer);

  @protected
  RsKdeConnectIdentity sse_decode_rs_kde_connect_identity(SseDeserializer deserializer);

  @protected
  RsKdeConnectTrustedDevice sse_decode_rs_kde_connect_trusted_device(SseDeserializer deserializer);

  @protected
  RsKdeNotification sse_decode_rs_kde_notification(SseDeserializer deserializer);

  @protected
  RsKdeSmsAttachment sse_decode_rs_kde_sms_attachment(SseDeserializer deserializer);

  @protected
  RsKdeSmsConversation sse_decode_rs_kde_sms_conversation(SseDeserializer deserializer);

  @protected
  RsKdeSmsMessage sse_decode_rs_kde_sms_message(SseDeserializer deserializer);

  @protected
  RsKdeTelephonyEvent sse_decode_rs_kde_telephony_event(SseDeserializer deserializer);

  @protected
  RsLanCandidate sse_decode_rs_lan_candidate(SseDeserializer deserializer);

  @protected
  RsRelayAddress sse_decode_rs_relay_address(SseDeserializer deserializer);

  @protected
  RsRelayAnywhereEvent sse_decode_rs_relay_anywhere_event(SseDeserializer deserializer);

  @protected
  RsRelayAnywhereFile sse_decode_rs_relay_anywhere_file(SseDeserializer deserializer);

  @protected
  RsRelayAnywhereListenerEvent sse_decode_rs_relay_anywhere_listener_event(SseDeserializer deserializer);

  @protected
  RsRelayIncomingFile sse_decode_rs_relay_incoming_file(SseDeserializer deserializer);

  @protected
  RsRelayLanPairingEvent sse_decode_rs_relay_lan_pairing_event(SseDeserializer deserializer);

  @protected
  RsRelayPathPreference sse_decode_rs_relay_path_preference(SseDeserializer deserializer);

  @protected
  RsRelayPeerAuth sse_decode_rs_relay_peer_auth(SseDeserializer deserializer);

  @protected
  RsRelayTransferEvent sse_decode_rs_relay_transfer_event(SseDeserializer deserializer);

  @protected
  RsRelayTransferFile sse_decode_rs_relay_transfer_file(SseDeserializer deserializer);

  @protected
  RsServerEvent sse_decode_rs_server_event(SseDeserializer deserializer);

  @protected
  RsSmsConversation sse_decode_rs_sms_conversation(SseDeserializer deserializer);

  @protected
  RsSmsMessage sse_decode_rs_sms_message(SseDeserializer deserializer);

  @protected
  RsStoredDevice sse_decode_rs_stored_device(SseDeserializer deserializer);

  @protected
  RsUploadEvent sse_decode_rs_upload_event(SseDeserializer deserializer);

  @protected
  RTCFileError sse_decode_rtc_file_error(SseDeserializer deserializer);

  @protected
  RTCSendFileResponse sse_decode_rtc_send_file_response(SseDeserializer deserializer);

  @protected
  RTCStatus sse_decode_rtc_status(SseDeserializer deserializer);

  @protected
  SecurityContext sse_decode_security_context(SseDeserializer deserializer);

  @protected
  SessionEndReasonV2 sse_decode_session_end_reason_v_2(SseDeserializer deserializer);

  @protected
  TlsConfig sse_decode_tls_config(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WebI18n sse_decode_web_i_18_n(SseDeserializer deserializer);

  @protected
  WebParams sse_decode_web_params(SseDeserializer deserializer);

  @protected
  WebSendParams sse_decode_web_send_params(SseDeserializer deserializer);

  @protected
  WsServerMessage sse_decode_ws_server_message(SseDeserializer deserializer);

  @protected
  WsServerSdpMessage sse_decode_ws_server_sdp_message(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    Dart2RustStreamReceiver self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    Dart2RustStreamSink self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection(
    LsSignalingConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver(
    RtcFileReceiver self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender(
    RtcFileSender self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController(
    RtcReceiveController self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(
    RtcSendController self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken(
    RsCancellationToken self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery(RsDiscovery self, SseSerializer serializer);

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(RsHttpClient self, SseSerializer serializer);

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer(RsHttpServer self, SseSerializer serializer);

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect(RsKdeConnect self, SseSerializer serializer);

  @protected
  void sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    Dart2RustStreamSink self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(
    RtcSendController self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection(
    LsSignalingConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver(
    RtcFileReceiver self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender(RtcFileSender self, SseSerializer serializer);

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController(
    RtcReceiveController self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(
    RtcSendController self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken(
    RsCancellationToken self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery(RsDiscovery self, SseSerializer serializer);

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(RsHttpClient self, SseSerializer serializer);

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer(RsHttpServer self, SseSerializer serializer);

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect(RsKdeConnect self, SseSerializer serializer);

  @protected
  void
  sse_encode_DartFn_Inputs_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection_Output_unit_AnyhowException(
    FutureOr<void> Function(LsSignalingConnection) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_String_None(Map<String, String> self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_file_dto_None(Map<String, FileDto> self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    Dart2RustStreamReceiver self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    Dart2RustStreamSink self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection(
    LsSignalingConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver(RtcFileReceiver self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender(RtcFileSender self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController(
    RtcReceiveController self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(RtcSendController self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken(
    RsCancellationToken self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery(RsDiscovery self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(RsHttpClient self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer(RsHttpServer self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect(RsKdeConnect self, SseSerializer serializer);

  @protected
  void sse_encode_Set_String_None(Set<String> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver_Sse(
    RustStreamSink<RtcFileReceiver> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_f_64_Sse(RustStreamSink<double> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(RustStreamSink<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_rs_continuity_event_Sse(RustStreamSink<RsContinuityEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_rs_continuity_host_request_Sse(RustStreamSink<RsContinuityHostRequest> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_rs_hash_file_event_Sse(RustStreamSink<RsHashFileEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_rs_kde_connect_event_Sse(RustStreamSink<RsKdeConnectEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_rs_relay_anywhere_event_Sse(RustStreamSink<RsRelayAnywhereEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_rs_relay_anywhere_listener_event_Sse(RustStreamSink<RsRelayAnywhereListenerEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_rs_relay_lan_pairing_event_Sse(RustStreamSink<RsRelayLanPairingEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_rs_relay_transfer_event_Sse(RustStreamSink<RsRelayTransferEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_rs_server_event_Sse(RustStreamSink<RsServerEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_rs_stored_device_Sse(RustStreamSink<RsStoredDevice> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_rs_upload_event_Sse(RustStreamSink<RsUploadEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_rtc_file_error_Sse(RustStreamSink<RTCFileError> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_rtc_status_Sse(RustStreamSink<RTCStatus> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_ws_server_message_Sse(RustStreamSink<WsServerMessage> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    Dart2RustStreamReceiver self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_client_info(ClientInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_client_info_without_id(ClientInfoWithoutId self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_device_type(DeviceType self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_expecting_public_key(ExpectingPublicKey self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_file_dto(FileDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_file_metadata(FileMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_pin_config(PinConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_prepare_upload_request_dto(PrepareUploadRequestDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_prepare_upload_response_dto(PrepareUploadResponseDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_proposing_client_info(ProposingClientInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_register_dto(RegisterDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_register_dto_v_2(RegisterDtoV2 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rs_call_state(RsCallState self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rs_capability_manifest(RsCapabilityManifest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rs_discovered_device(RsDiscoveredDevice self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rs_http_client_error(RsHttpClientError self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rs_kde_connect_identity(RsKdeConnectIdentity self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rs_kde_sms_message(RsKdeSmsMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rs_kde_telephony_event(RsKdeTelephonyEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rs_sms_message(RsSmsMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rtc_send_file_response(RTCSendFileResponse self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tls_config(TlsConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_web_params(WebParams self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_web_send_params(WebSendParams self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ws_server_sdp_message(WsServerSdpMessage self, SseSerializer serializer);

  @protected
  void sse_encode_client_info(ClientInfo self, SseSerializer serializer);

  @protected
  void sse_encode_client_info_without_id(ClientInfoWithoutId self, SseSerializer serializer);

  @protected
  void sse_encode_device_log_kind(DeviceLogKind self, SseSerializer serializer);

  @protected
  void sse_encode_device_type(DeviceType self, SseSerializer serializer);

  @protected
  void sse_encode_expecting_public_key(ExpectingPublicKey self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_file_dto(FileDto self, SseSerializer serializer);

  @protected
  void sse_encode_file_metadata(FileMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_key_pair(KeyPair self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_client_info(List<ClientInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_dto(List<FileDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_file_dto(List<(String, FileDto)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_string(List<(String, String)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_capability_entry(List<RsCapabilityEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_device_channel(List<RsDeviceChannel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_device_log(List<RsDeviceLog> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_kde_connect_device(List<RsKdeConnectDevice> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_kde_connect_trusted_device(List<RsKdeConnectTrustedDevice> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_kde_notification(List<RsKdeNotification> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_kde_sms_attachment(List<RsKdeSmsAttachment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_kde_sms_conversation(List<RsKdeSmsConversation> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_kde_sms_message(List<RsKdeSmsMessage> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_lan_candidate(List<RsLanCandidate> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_relay_anywhere_file(List<RsRelayAnywhereFile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_relay_incoming_file(List<RsRelayIncomingFile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_relay_transfer_file(List<RsRelayTransferFile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_sms_conversation(List<RsSmsConversation> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rs_sms_message(List<RsSmsMessage> self, SseSerializer serializer);

  @protected
  void sse_encode_ls_http_client_version(LsHttpClientVersion self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    Dart2RustStreamReceiver? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_device_type(DeviceType? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_expecting_public_key(ExpectingPublicKey? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_file_metadata(FileMetadata? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_pin_config(PinConfig? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_prepare_upload_response_dto(PrepareUploadResponseDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rs_kde_sms_message(RsKdeSmsMessage? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_tls_config(TlsConfig? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_web_params(WebParams? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_web_send_params(WebSendParams? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_pin_config(PinConfig self, SseSerializer serializer);

  @protected
  void sse_encode_prepare_upload_request_dto(PrepareUploadRequestDto self, SseSerializer serializer);

  @protected
  void sse_encode_prepare_upload_response_dto(PrepareUploadResponseDto self, SseSerializer serializer);

  @protected
  void sse_encode_prepare_upload_result(PrepareUploadResult self, SseSerializer serializer);

  @protected
  void sse_encode_proposing_client_info(ProposingClientInfo self, SseSerializer serializer);

  @protected
  void sse_encode_protocol_type(ProtocolType self, SseSerializer serializer);

  @protected
  void
  sse_encode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dart_2_rust_stream_sink_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dart_2_rust_stream_receiver(
    (Dart2RustStreamSink, Dart2RustStreamReceiver) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_file_dto((String, FileDto) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string((String, String) self, SseSerializer serializer);

  @protected
  void sse_encode_register_dto(RegisterDto self, SseSerializer serializer);

  @protected
  void sse_encode_register_dto_v_2(RegisterDtoV2 self, SseSerializer serializer);

  @protected
  void sse_encode_register_response_dto(RegisterResponseDto self, SseSerializer serializer);

  @protected
  void sse_encode_relay_identity_material(RelayIdentityMaterial self, SseSerializer serializer);

  @protected
  void sse_encode_result_with_public_key_register_response_dto(ResultWithPublicKeyRegisterResponseDto self, SseSerializer serializer);

  @protected
  void sse_encode_rs_call_action(RsCallAction self, SseSerializer serializer);

  @protected
  void sse_encode_rs_call_phase(RsCallPhase self, SseSerializer serializer);

  @protected
  void sse_encode_rs_call_state(RsCallState self, SseSerializer serializer);

  @protected
  void sse_encode_rs_capability_entry(RsCapabilityEntry self, SseSerializer serializer);

  @protected
  void sse_encode_rs_capability_manifest(RsCapabilityManifest self, SseSerializer serializer);

  @protected
  void sse_encode_rs_capability_state(RsCapabilityState self, SseSerializer serializer);

  @protected
  void sse_encode_rs_charging_state(RsChargingState self, SseSerializer serializer);

  @protected
  void sse_encode_rs_clipboard_mode(RsClipboardMode self, SseSerializer serializer);

  @protected
  void sse_encode_rs_continuity_capability(RsContinuityCapability self, SseSerializer serializer);

  @protected
  void sse_encode_rs_continuity_event(RsContinuityEvent self, SseSerializer serializer);

  @protected
  void sse_encode_rs_continuity_host_request(RsContinuityHostRequest self, SseSerializer serializer);

  @protected
  void sse_encode_rs_device_channel(RsDeviceChannel self, SseSerializer serializer);

  @protected
  void sse_encode_rs_device_log(RsDeviceLog self, SseSerializer serializer);

  @protected
  void sse_encode_rs_discovered_device(RsDiscoveredDevice self, SseSerializer serializer);

  @protected
  void sse_encode_rs_hash_file_event(RsHashFileEvent self, SseSerializer serializer);

  @protected
  void sse_encode_rs_http_client_error(RsHttpClientError self, SseSerializer serializer);

  @protected
  void sse_encode_rs_kde_connect_device(RsKdeConnectDevice self, SseSerializer serializer);

  @protected
  void sse_encode_rs_kde_connect_event(RsKdeConnectEvent self, SseSerializer serializer);

  @protected
  void sse_encode_rs_kde_connect_identity(RsKdeConnectIdentity self, SseSerializer serializer);

  @protected
  void sse_encode_rs_kde_connect_trusted_device(RsKdeConnectTrustedDevice self, SseSerializer serializer);

  @protected
  void sse_encode_rs_kde_notification(RsKdeNotification self, SseSerializer serializer);

  @protected
  void sse_encode_rs_kde_sms_attachment(RsKdeSmsAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_rs_kde_sms_conversation(RsKdeSmsConversation self, SseSerializer serializer);

  @protected
  void sse_encode_rs_kde_sms_message(RsKdeSmsMessage self, SseSerializer serializer);

  @protected
  void sse_encode_rs_kde_telephony_event(RsKdeTelephonyEvent self, SseSerializer serializer);

  @protected
  void sse_encode_rs_lan_candidate(RsLanCandidate self, SseSerializer serializer);

  @protected
  void sse_encode_rs_relay_address(RsRelayAddress self, SseSerializer serializer);

  @protected
  void sse_encode_rs_relay_anywhere_event(RsRelayAnywhereEvent self, SseSerializer serializer);

  @protected
  void sse_encode_rs_relay_anywhere_file(RsRelayAnywhereFile self, SseSerializer serializer);

  @protected
  void sse_encode_rs_relay_anywhere_listener_event(RsRelayAnywhereListenerEvent self, SseSerializer serializer);

  @protected
  void sse_encode_rs_relay_incoming_file(RsRelayIncomingFile self, SseSerializer serializer);

  @protected
  void sse_encode_rs_relay_lan_pairing_event(RsRelayLanPairingEvent self, SseSerializer serializer);

  @protected
  void sse_encode_rs_relay_path_preference(RsRelayPathPreference self, SseSerializer serializer);

  @protected
  void sse_encode_rs_relay_peer_auth(RsRelayPeerAuth self, SseSerializer serializer);

  @protected
  void sse_encode_rs_relay_transfer_event(RsRelayTransferEvent self, SseSerializer serializer);

  @protected
  void sse_encode_rs_relay_transfer_file(RsRelayTransferFile self, SseSerializer serializer);

  @protected
  void sse_encode_rs_server_event(RsServerEvent self, SseSerializer serializer);

  @protected
  void sse_encode_rs_sms_conversation(RsSmsConversation self, SseSerializer serializer);

  @protected
  void sse_encode_rs_sms_message(RsSmsMessage self, SseSerializer serializer);

  @protected
  void sse_encode_rs_stored_device(RsStoredDevice self, SseSerializer serializer);

  @protected
  void sse_encode_rs_upload_event(RsUploadEvent self, SseSerializer serializer);

  @protected
  void sse_encode_rtc_file_error(RTCFileError self, SseSerializer serializer);

  @protected
  void sse_encode_rtc_send_file_response(RTCSendFileResponse self, SseSerializer serializer);

  @protected
  void sse_encode_rtc_status(RTCStatus self, SseSerializer serializer);

  @protected
  void sse_encode_security_context(SecurityContext self, SseSerializer serializer);

  @protected
  void sse_encode_session_end_reason_v_2(SessionEndReasonV2 self, SseSerializer serializer);

  @protected
  void sse_encode_tls_config(TlsConfig self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_web_i_18_n(WebI18n self, SseSerializer serializer);

  @protected
  void sse_encode_web_params(WebParams self, SseSerializer serializer);

  @protected
  void sse_encode_web_send_params(WebSendParams self, SseSerializer serializer);

  @protected
  void sse_encode_ws_server_message(WsServerMessage self, SseSerializer serializer);

  @protected
  void sse_encode_ws_server_sdp_message(WsServerSdpMessage self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) => RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiverPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiverPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiverPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiver =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamReceiverPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSinkPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSinkPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSinkPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSink =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDart2RustStreamSinkPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnectionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnectionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnectionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnection =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLsSignalingConnectionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiverPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiverPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiverPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiver =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileReceiverPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSenderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSenderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSenderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSender =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCFileSenderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveControllerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveControllerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveControllerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveController =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCReceiveControllerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendControllerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendControllerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendControllerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendController =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRTCSendControllerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationTokenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationTokenPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationTokenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationToken =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsCancellationTokenPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscoveryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscoveryPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscoveryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscovery =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsDiscoveryPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClient =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServer =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsHttpServerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnectPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_relay_isolates_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnect =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRsKdeConnectPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
