name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Relay
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Relay.Relay
          installers-regex: 'Relay-(?!CLI-).*\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
      - name: Publish Relay CLI
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Relay.Relay.CLI
          installers-regex: 'Relay-CLI-.*\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
